--POPULATES ROLE TABLE
INSERT INTO ROLE VALUES(1, 'Program Lead', 'Responsable de Programme');
INSERT INTO ROLE VALUES(2, 'Program Officer', 'Agent de Programme');

--POPULATES ROLE AUDITING TABLE AND INSERTS THE CORRESPONDING METADATA INTO REVISION_INFO TABLE
INSERT INTO REVISION_INFO VALUES (1, CONVERT(VARCHAR(19), SYSDATETIME(), 120), 'app-admim');
INSERT INTO ROLE_HISTORY VALUES (1, 1, 0, 'Program Lead', 'Responsable de Programme');
INSERT INTO ROLE_HISTORY VALUES (2, 1, 0, 'Program Officer', 'Agent de Programme');
