--POPULATES BUSINESS_UNIT TABLE
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID,DISTRIBUTION) VALUES (1, 'MCT', 'FR MCT', 'MCT', 'MCT', 3, 'rpp@nserc-crsng.gc.ca');
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID,DISTRIBUTION) VALUES (2, 'EER', 'FR EER', 'EER', 'EER', 2, 'rpp@nserc-crsng.gc.ca');
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (3, 'ICSP', 'FR ICSP', 'ICSP', 'ICSP', 2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (4, 'SF', 'FR SF', 'SF', 'SF', 2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (5, 'MEPS', 'FR MEPS', 'MEPS', 'MEPS', 2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID,DISTRIBUTION) VALUES (6, 'CCPP', 'FR CCPP', 'CCPP', 'CCPP', 2, 'i2i@nserc-crsng.gc.ca');
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID,DISTRIBUTION) VALUES (7, 'NCE', 'FR NCE', 'NCE', 'NCE', 3, 'info@nce-rce.gc.ca, alex.pigeon@nce-rce.gc.ca');
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID,DISTRIBUTION) VALUES (8, 'RP', 'FR RP', 'RP', 'RP', 2, 'alliance@nserc-crsng.gc.ca');
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (9, 'ELS', 'FR ELS', 'ELS', 'ELS', 2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID,DISTRIBUTION) VALUES (10, 'RGPD', 'FR RGPD', 'RGPD','RGPD', 1, 'partnershipgrants@sshrc-crsh.gc.ca, partnershipdevelopment@sshrc-crsh.gc.ca, colleges@nserc-crsng.gc.ca, connection@sshrc-crsh.gc.ca, partnershipengagegrants@sshrc-crsh.gc.ca');
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID,DISTRIBUTION) VALUES (11, 'TIPS', 'FR TIPS', 'TIPS','TIPS', 1, 'information@chairs-chaires.gc.ca');
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID,DISTRIBUTION) VALUES (12, 'FCD', 'FR FCD', 'FCD','FCD', 1, 'KSG-SSC@sshrc-crsh.gc.ca');
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID,DISTRIBUTION) VALUES (13, 'RTP', 'FR RTP', 'RTP','RTP', 1, 'fellowships@sshrc-crsh.gc.ca');
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID,DISTRIBUTION) VALUES (14, 'Comms', 'FR Comms', 'COMMS','COMMS', 1, 'storytellers@sshrc-crsh.gc.ca');

--POPULATES BUSINESS_UNIT AUDITING TABLE AND INSERTS THE CORRESPONDING METADATA INTO REVISION_INFO TABLE
INSERT INTO REVISION_INFO VALUES (4, CONVERT(VARCHAR(19), SYSDATETIME(), 120), 'app-admin');
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (1, 4, 0, 'MCT', 'FR MCT', 'MCT', 'MCT', 3, 'rpp@nserc-crsng.gc.ca');
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (2, 4, 0, 'EER', 'FR EER', 'EER', 'EER', 2, 'rpp@nserc-crsng.gc.ca');
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (3, 4, 0, 'ICSP', 'FR ICSP', 'ICSP', 'ICSP', 2, NULL);
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (4, 4, 0, 'SF', 'FR SF','SF', 'SF', 2, NULL);
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (5, 4, 0, 'MEPS', 'FR MEPS', 'MEPS', 'MEPS', 2, NULL);
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (6, 4, 0, 'CCPP', 'FR CCPP', 'CCPP', 'CCPP', 2, 'i2i@nserc-crsng.gc.ca');
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (7, 4, 0, 'NCE', 'FR NCE', 'NCE', 'NCE', 3, 'info@nce-rce.gc.ca, alex.pigeon@nce-rce.gc.ca');
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (8, 4, 0, 'RP', 'FR RP', 'RP', 'RP', 2, 'alliance@nserc-crsng.gc.ca');
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (9, 4, 0, 'ELS', 'FR ELS', 'ELS', 'ELS', 2, NULL);
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (10, 4, 0, 'RGPD', 'FR RGPD', 'RGPD', 'RGPD', 1, 'partnershipgrants@sshrc-crsh.gc.ca, partnershipdevelopment@sshrc-crsh.gc.ca, colleges@nserc-crsng.gc.ca, connection@sshrc-crsh.gc.ca, partnershipengagegrants@sshrc-crsh.gc.ca');
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (11, 4, 0, 'TIPS', 'FR TIPS', 'TIPS', 'TIPS', 1, 'information@chairs-chaires.gc.ca');
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (12, 4, 0, 'FCD', 'FR FCD', 'FCD', 'FCD', 1, 'KSG-SSC@sshrc-crsh.gc.ca');
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (13, 4, 0, 'RTP', 'FR RTP', 'RTP', 'RTP', 1, 'fellowships@sshrc-crsh.gc.ca');
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (14, 4, 0, 'Comms', 'FR Comms', 'COMMS', 'COMMS', 1, 'storytellers@sshrc-crsh.gc.ca');