-- POPULTATES GRANTING_SYSTEM TABLE
INSERT INTO GRANTING_SYSTEM VALUES (1, 'RP1', 'Research Portal', 'Portail de Recherche');
INSERT INTO GRANTING_SYSTEM VALUES (2, 'CRM', 'CRM', 'CRM');
INSERT INTO GRANTING_SYSTEM VALUES (3, 'SSHRC Online', 'SSHRC Online', 'SSHRC Online');
INSERT INTO GRANTING_SYSTEM VALUES (4, 'AMIS', 'AMIS', 'AMIS');
INSERT INTO GRANTING_SYSTEM VALUES (5, 'NSERC Online', 'NSERC Online', 'NSERC Online');
INSERT INTO GRANTING_SYSTEM VALUES (6, 'NAMIS', 'NAMIS', 'NAMIS');
INSERT INTO GRANTING_SYSTEM VALUES (7, 'CIMS', 'Corporate Inventory Management System', 'Corporate Inventory Management System');
INSERT INTO GRANTING_SYSTEM VALUES (8, 'ResearchNet', 'ResearchNet', 'ResearchNet');
INSERT INTO GRANTING_SYSTEM VALUES (9, 'Convergence', 'Convergence', 'Convergence');
INSERT INTO GRANTING_SYSTEM VALUES (10, 'SP Secure Upload', 'SharePoint Secure Upload', 'Téléchargement Sécurisé SharePoint');
INSERT INTO GRANTING_SYSTEM VALUES (11, 'SP Review', 'SharePoint Review', 'Examen de SharePoint');
INSERT INTO GRANTING_SYSTEM VALUES (12, 'N/A', 'N/A', 'N/A');

--POPULATES GRANTING_SYSTEM AUDITING TABLE AND INSERTS THE CORRESPONDING METADATA INTO REVISION_INFO TABLE
INSERT INTO REVISION_INFO VALUES (3, CONVERT(VARCHAR(19), SYSDATETIME(), 120), 'app-admin');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (1, 3, 0, 'RP1', 'Research Portal', 'Portail de Recherche');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (2, 3, 0, 'CRM', 'CRM', 'CRM');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (3, 3, 0, 'SSHRC Online', 'SSHRC Online', 'SSHRC Online');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (4, 3, 0, 'AMIS', 'AMIS', 'AMIS');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (5, 3, 0, 'NSERC Online', 'NSERC Online', 'NSERC Online');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (6, 3, 0, 'NAMIS', 'NAMIS', 'NAMIS');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (7, 3, 0, 'CIMS', 'Corporate Inventory Management System', 'Corporate Inventory Management System');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (8, 3, 0, 'ResearchNet', 'ResearchNet', 'ResearchNet');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (9, 3, 0, 'Convergence', 'Convergence', 'Convergence');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (10, 3, 0, 'SP Secure Upload', 'SharePoint Secure Upload', 'Téléchargement Sécurisé SharePoint');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (11, 3, 0, 'SP Review', 'SharePoint Review', 'Examen de SharePoint');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (12, 3, 0, 'N/A', 'N/A', 'N/A');
