--POPULATES GRATING_STAGE TABLE
INSERT INTO GRANTING_STAGE VALUES (1, 'ADMIN', 'ADMIN');
INSERT INTO GRANTING_STAGE VALUES (2, 'APPLY', 'APPLY');
INSERT INTO GRANTING_STAGE VALUES (3, 'ASSESS', 'ASSESS');
INSERT INTO GRANTING_STAGE VALUES (4, 'AWARD', 'AWARD');
INSERT INTO GRANTING_STAGE VALUES (5, 'AQUIT', 'AQUIT');
