--POPULATES FUNDING_OPPORTUNITY TABLE
INSERT INTO FUNDING_OPPORTUNITY VALUES (1, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Collaborative Health Research Projects (CHRP) (5640)', NULL, NULL, 0, 0, 1);
INSERT INTO FUNDING_OPPORTUNITY VALUES (2, NULL, NULL, 0, 0, 0, 'IPPH Urban Housing and Health Trainee Research Awards', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (3, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Chairs in Design Engineering (research and salary)', 'Chaires en génie de la conception', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (4, 'Open', 'Research Grants', 0, 0, 0, 'Unique Initiatives Fund (5860)', 'Fonds d''initiatives uniques', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (5, 'Open', 'Research Grants', 0, 0, 0, 'Chairs for Women in Science and Engineering (CWSE)', 'Programme de chaires pour les femmes en sciences et en génie', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (6, '1/YR', 'Scholarships', 0, 0, 0, 'CMHC Postdoctoral Fellowships', 'Programme de bourses de recherche sur le logement de la SCHL.', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (7, '1/YR', 'Scholarships', 0, 0, 0, 'Foreign Study Supplements in Taiwan (FSS-Taiwan) (SIT) (5050)', 'Suppléments pour études à Taïwan', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (8, '1/YR', 'Scholarships', 0, 0, 0, 'JSPS - Postdoctoral Fellowships Program (JSPSF) (4933)', 'Bourses postdoctorales de la Société japonaise pour la promotion de la science', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (9, 'Open', 'Scholarships', 0, 0, 0, 'Aboriginal Ambassadors in the Natural Sciences and Engineering (AANSE) (6610)', 'Bourse pour ambassadeurs autochtones des sciences naturelles et du génie', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (10, '1/YR', 'Prize', 0, 0, 0, 'Brockhouse Canada Prize (5225)', 'Prix Brockhouse du Canada', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (11, '1/YR', NULL, 0, 0, 0, 'Canadian Institute for Theoretical Astrophysics Support Program (CITA) (5632)', 'Programme d''appui à l''Institut canadien d''astrophysique théorique', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (12, '1/YR', 'Fellowships', 0, 0, 0, 'EWR Steacie Fellowships (Research and Salary) (SMFSA-) (5265)', 'Bourses commémoratives E.W.R. Steacie', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (13, '1/YR', 'Scholarships', 0, 0, 0, 'GENDER-NET Plus', 'ERA-NET Cofund', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (14, '1/YR', 'Prize', 0, 0, 0, 'Herzberg Canada Gold Medal for Science and Engineering (5300)', 'Médaille d''or Gerhard-Herzberg en sciences et en génie du Canada', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (15, '1/YR', 'Prize', 0, 0, 0, 'John C. Polanyi Award (5735)', 'Prix John-C.-Polanyi du CRSNG', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (16, '1/YR', 'Prize', 0, 0, 0, 'NSERC Award for Science Promotion (NASPI)', 'Prix du CRSNG - Promotion des sciences', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (17, '1/YR', 'Prize', 0, 0, 0, 'NSERC Award for Science Promotion (NASPO) (6780)', 'Prix du CRSNG - Promotion des sciences', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (18, '1/YR', 'Scholarships', 0, 0, 0, 'PromoScience (5390)', 'Promotion des sciences', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (19, '1/YR', 'Supplement', 0, 0, 0, 'PromoScience Supplements (PSC)', NULL, NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (20, '1/YR', 'Supplement', 0, 0, 0, 'Science Literacy Week (SLW) (PSSLW)', 'Semaine de la culture scientifique', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (21, '1/YR', 'Supplement', 0, 0, 0, 'Science Odyssey Supplements (SOS) (PSSOS)', 'Odyssée des sciences', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (22, NULL, 'Scholarships', 0, 0, 0, 'Student Amassadors (NSA) (MFNSA) (5370)', 'Étudiants ambassadeurs du CRSNG', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (23, 'Open', 'Scholarships', 0, 0, 0, 'Young Innovators (MFNYI)', NULL, NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (24, 'Open', 'Partnerships Programs', 0, 0, 0, 'Collaborative Research and Development Grants (CRD) (6415)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (25, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Community & College Social Innovation Fund (CCSIF) (6017)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY VALUES (26, 'Open', 'Partnerships Programs', 0, 0, 0, 'Engage for Colleges (CARD1) (6006)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY VALUES (27, 'Open', 'Partnerships Programs', 0, 0, 0, 'Engage for Universities (EGP) (6430)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY VALUES (28, 'Open', 'Partnerships Programs', 0, 0, 0, 'Engage Plus Grants for Colleges (CEGP2) (6015)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY VALUES (29, 'Open', 'Partnerships Programs', 0, 0, 0, 'Engage Plus Grants for Universities (EGP2) (6432)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY VALUES (30, 'Open', 'Partnerships Programs', 0, 0, 0, 'Experience Awards (previously IUSRA)(USRAI) (6030)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY VALUES (31, '1+/YR', 'Scholarships', 0, 0, 0, 'Undergraduate Student Research Awards (USRA) (URU) (6862)', NULL, NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (32, '1+/YR', NULL, 0, 0, 0, 'Idea to Innovation (I2I) - (I2IPJ) (6036)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY VALUES (33, 'Open', 'Partnerships Programs', 0, 0, 0, 'Industrial Research Chairs (IRC) (6235)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (34, '1/YR', 'Scholarships', 0, 0, 0, 'Postdoctoral Fellowships (PDF) (6790)', NULL, NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (35, '1/YR', 'Scholarships', 0, 0, 0, 'Postgraduate Scholarships - Doctoral PGS-D2 (Direct and University) (6798)', NULL, NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (36, '1/YR', 'Scholarships', 0, 0, 0, 'Postgraduate Scholarships - Doctoral PGS-D3 (Direct and University) (6799)', NULL, NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (37, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Strategic Parnerships - Networks (SPG-N)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (38, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Strategic Partnerships - Projects (SPG-P)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (39, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Applied Research Tools and Instruments Grants (ARTI) (CARTI) (6004)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY VALUES (40, '1/YR+', NULL, 0, 0, 0, 'Belmont Forum (BFAOR) (5807)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (41, '1/YR+', NULL, 0, 0, 0, 'Belmont Forum (BFBIO) (5808)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (42, '1/Year', 'Scholarships', 0, 0, 0, 'CREATE (6648)', NULL, NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (43, 'Open', NULL, 0, 0, 0, 'DND/NSERC Research Partnership (DNDPJ) (6467)', NULL, NULL, 0, 0, 9);
INSERT INTO FUNDING_OPPORTUNITY VALUES (44, '1/YR+', NULL, 0, 0, 0, 'Human Frontiers in Science Program (HFSP) (5700)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (45, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Innovation Enhancement Grants - Build (IE) CCIP) (6013)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY VALUES (46, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Innovation Enhancement Grants - Entry (IE) (CCIPE) (6008)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY VALUES (47, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Innovation Enhancement Grants - Extend (IE) (CCIPX) (6016)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY VALUES (48, '1/YR', 'Supplement', 0, 0, 0, 'Ship Time (RGPST) (5822)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (49, '1/YR', NULL, 0, 0, 0, 'Strategic Network Grants Program (NETGP) (6070)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (50, '1/YR', NULL, 0, 0, 0, 'Subatomic Physics - Individual (SAPIN) (5840)', 'Programme de subventions à la découverte en physique subatomique', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (51, '1/YR', NULL, 0, 0, 0, 'Synergy Awards (Colleges) CSYN (6477)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (52, '1/YR+', NULL, 0, 0, 0, 'Thematic Resources Support in Mathematics and Statistics (CTRMS)', 'Programme d''appui aux ressources thématiques en mathématiques et en statistique', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (53, '1/YR', NULL, 0, 0, 0, 'Discovery Development Grant (DDG)', NULL, NULL, 0, 0, 9);
INSERT INTO FUNDING_OPPORTUNITY VALUES (54, '1/YR', 'Supplement', 0, 0, 0, 'Discovery Grants - Northern Research Supplement (NRS)', 'Programme de suppléments aux subventions à la découverte en recherche nordique', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (55, '1/YR', NULL, 0, 0, 0, 'Discovery Grants (DG) (RGPIN)', 'Programme de subventions à la découverte', NULL, 0, 0, 9);
INSERT INTO FUNDING_OPPORTUNITY VALUES (56, '1/YR', 'Supplement', 0, 0, 0, 'DND/NSERC Discovery Grant Supplement (DGDND)', 'Supplément aux subventions à la découverte MDN-CRSNG', NULL, 0, 0, 9);
INSERT INTO FUNDING_OPPORTUNITY VALUES (57, '1/YR', NULL, 0, 0, 0, 'Research Tools and Instruments (RTI)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (58, '1/YR', NULL, 0, 0, 0, 'Subatomic Physics - Projects (SAPPJ) - small and large projects', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (59, '1/YR', NULL, 0, 0, 0, 'Subatomic Physics - Research Tools and Instruments (SAP-RTI Cat. 1)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (60, '1/YR', NULL, 0, 0, 0, 'Subatomic Physics - Research Tools and Instruments (SAP-RTI Cat. 2 & 3)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (61, '1/YR', NULL, 0, 0, 0, 'Subatomic Physics Major Resources Support (SAPMR)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (62, 'Open', 'Partnerships Programs', 0, 0, 0, 'Connect Grants Level 1 for colleges', 'Subventions Connexion Niveau 1 de College', NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY VALUES (63, 'Open', 'Partnerships Programs', 0, 0, 0, 'Connect Grants Level 1 for universities', 'Subventions Connexion Niveau 1 des Universities', NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY VALUES (64, 'Open', 'Partnerships Programs', 0, 0, 0, 'Connect Grants Level 2 for colleges', 'Subventions Connexion Niveau 2 de College', NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY VALUES (65, 'Open', 'Partnerships Programs', 0, 0, 0, 'Connect Grants Level 2 for universities', 'Subventions Connexion Niveau 2 des Universities', NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY VALUES (66, '1/YR', 'Scholarships', 0, 0, 0, 'L''Oréal-UNESCO For Women in Science - NSERC Postdoctoral Fellowship Supplement', 'Supplément du CRSNG et de L''Oréal-UNESCO pour les femmes et la science', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (67, '1/YR', 'Scholarships', 0, 0, 0, 'STEAM Horizon Awards (6850)', 'Prix Horizon STIAM', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (68, '1/YR+', NULL, 0, 0, 0, 'Discovery Frontiers ) (RGPBB)', 'Frontières de la découverte', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (69, '1/YR+', NULL, 0, 0, 0, 'Discovery Frontiers (RGPDD)', 'Frontières de la découverte', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (70, '1/YR+', NULL, 0, 0, 0, 'Discovery Frontiers (RGPDF)', 'Frontières de la découverte', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (71, '1/YR+', NULL, 0, 0, 0, 'Discovery Frontiers (RGPGR)', 'Frontières de la découverte', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (72, '1/YR', 'Supplement', 0, 0, 0, 'Discovery Grants - Accelerator Supplement (DAS)', 'Programme de suppléments d''accélération à la découverte', NULL, 0, 0, 9);
INSERT INTO FUNDING_OPPORTUNITY VALUES (73, NULL, NULL, 0, 0, 0, 'Science Exposed', 'La preuve par l''image', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (74, NULL, NULL, 0, 0, 0, 'Science, Action!', 'Science, Action!', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (75, NULL, NULL, 0, 0, 0, 'College Special Initiatives (CSI)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (76, '1/Year', 'Fellowships', 0, 0, 0, 'EWR Steacie Fellowships (Research and Salary) (SMFSU) (5265)', 'Bourses commémoratives E.W.R. Steacie', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (77, NULL, 'Industrial Research Chairs (IRCPJ) (6235)', 0, 0, 0, 'IRC', 'professeurs-chercheurs industriels', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (78, NULL, 'Research Grants', 0, 0, 0, 'Industrial Research Chairs (IRCSA) (6235)', 'Subventions de professeurs-chercheurs industriels', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (79, NULL, NULL, 0, 0, 0, 'Parental Leave - Research Grants', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (80, NULL, NULL, 0, 0, 0, 'Parental Leave - Scholarships & Fellowships', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (81, '1/YR', NULL, 0, 0, 0, 'Synergy Awards (Universities) (SYN) (5239)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (82, '2/YR', NULL, 0, 0, 0, 'Canada Research Chairs (CRC)', 'Chaires de recherche du Canada', NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY VALUES (83, '1/YR+', NULL, 0, 0, 0, 'Connections (HSSFC) (650)', 'Lauréate du prix Connexion', NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (84, '1/YR+', 'Research Grants', 0, 0, 0, 'Knowledge Synthesis Grant (872)', 'Subventions de synthèse des connaissances', NULL, 0, 0, 12);
INSERT INTO FUNDING_OPPORTUNITY VALUES (85, '1/YR', NULL, 0, 0, 0, 'Canada 150 Research Chairs Program', 'Chaires de recherche Canada 150', NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY VALUES (86, '1/YR', NULL, 0, 0, 0, 'Canada Excellence Research Chairs (CERC)', 'Chaires d''excellence en recherche du Canada', NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY VALUES (87, '1/YR', NULL, 0, 0, 0, 'Canada First Research Excellence Fund (CFREF)', 'Fonds d''excellence en recherche Apogée Canada', NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY VALUES (88, '1/YR', 'Prize', 0, 0, 0, 'Impact Awards - Connection (780)', 'Prix Impacts du CRSH Prix Connexion', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (89, '1/YR', 'Prize', 0, 0, 0, 'Impact Awards - Gold Medal (758)', 'Prix Impacts du CRSH Médaille d''or', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (90, '1/YR', 'Prize', 0, 0, 0, 'Impact Awards - Insight (781)', 'Prix Impacts du CRSH Prix Savoir', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (91, '1/YR', 'Prize', 0, 0, 0, 'Impact Awards - Partnership 9782)', 'Prix Impacts du CRSH Prix Partenariat', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (92, '1/YR', 'Prize', 0, 0, 0, 'Impact Awards - Talent (783)', 'Prix Impacts du CRSH Prix Talent', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (93, '1/Year', NULL, 0, 0, 0, 'Indigenous Research Capacity and Reconciliation — Connection Grants', 'Appel à propositions spécial pour l''attribution des subventions Connexion - Capacité de recherche autochtone et réconciliation', NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (94, '1/YR', 'Research Grants', 0, 0, 0, 'Insight Development Grants (430)', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (95, '1/YR', NULL, 0, 0, 0, 'Nelson Mandela', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (96, '1/YR+', 'Research Grant', 0, 0, 0, 'SSHRC Institutional Grant (633)', 'Subventions institutionnelles du CRSH', NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (97, '1/Year', 'Prize', 0, 0, 0, 'Story Tellers', 'J''ai une histoire à raconter', NULL, 0, 0, 14);
INSERT INTO FUNDING_OPPORTUNITY VALUES (98, '1/YR', 'Supplement', 0, 0, 0, 'Bora Laskin National Fellowship (754)', 'Bourse canadienne Bora-Laskin', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (99, '1/YR', 'Supplement', 0, 0, 0, 'Jules and Gabrielle Léger (759)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (100, '1/YR', 'Supplement', 0, 0, 0, 'Queen''s Fellowship (220 or 321)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (101, '1/YR', 'Supplement', 0, 0, 0, 'Aileen D. Ross (230)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (102, '1/YR', 'Internships', 0, 0, 0, 'Mitacs Elevate', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (103, '1/YR+', NULL, 0, 0, 0, 'Aid to Scholarly Journals (651)', 'Aide aux revues savantes', NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (104, '1/YR', 'Fellowships', 0, 0, 0, 'Centre for International Governance Innovation (CIGI)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (105, '1/YR', 'Fellowships', 0, 0, 0, 'CMHC Housing research Training Awards', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (106, '1+/YR', NULL, 0, 0, 0, 'Connection Grants (611)', 'Subventions Connections', NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (107, 'Open', NULL, 0, 0, 0, 'Department of National Defense Research Initiative (877)', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (108, '1/YR', 'Scholarship', 0, 0, 0, 'Doctoral Awards - CGS; Direct; National (752)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (109, '1+/Yr', 'Research Grants', 0, 0, 0, 'Insight Grants (435)', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (110, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Partnership Development Grants (890)', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (111, '1+/YR', 'Partnerships Programs', 0, 0, 0, 'Partnership Engage Grant', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (112, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Partnership Grants - Stage 1', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (113, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Partnership Grants - Stage 2', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (114, '1/YR', 'Scholarships', 0, 0, 0, 'Postdoctoral Fellowships (756)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (115, 'Open', NULL, 0, 0, 0, 'Sports Participation Research Initative (862)', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (116, 'Open', NULL, 0, 0, 0, 'Parental Leave - Scholarships & Fellowships (SSHRC) (769)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (117, 'Open', NULL, 0, 0, 0, 'Parental Leave - Scholarships and Fellowships through grants (SSHRC)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (118, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Parliamentary Internship Program (750)', 'Programme de stage parlementaire', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (119, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Queen Elizabeth (774)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (120, '1/YR', NULL, 0, 0, 0, 'Special Initiatives Fund For Research Support And Collaboration', NULL, NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY VALUES (121, '1/YR', NULL, 0, 0, 0, 'Research Support Fund (RSF)', NULL, NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY VALUES (122, NULL, 'Partnerships Programs', 0, 0, 0, 'CECR Centres of Excellence for Commercialization and Research', ' Programme des centres d''excellence en commercialisation et en recherche', NULL, 0, 0, 7);
INSERT INTO FUNDING_OPPORTUNITY VALUES (123, '1+/YR', 'Scholarships', 0, 0, 0, 'Canada Graduate Scholarships Michael Smith Foreign Study Supplements (MSFSS)', 'Programme de bourses d''études supérieures du Canada - Suppléments pour études à l''étranger Michael-Smith', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (124, 'Open', 'Partnerships Programs', 0, 0, 0, 'Applied Research and Development Grants - Colleges (ARD)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY VALUES (125, '1/YR', 'Partnerships Programs', 0, 0, 0, 'College - University Idea to Innovation Grants (CU-I2I)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY VALUES (126, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Industrial Research Chairs for Colleges Grants (IRCC)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY VALUES (127, '1/YR', 'Supplement', 0, 0, 0, 'Alice Wilson', 'Alice Wilson', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (128, '1/YR', 'Scholarships', 0, 0, 0, 'Banting Postdoctoral Fellowships', 'Bourses postdoctorales Banting', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (129, '1/YR', 'Scholarships', 0, 0, 0, 'Vanier', NULL, NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (130, '1/YR', 'Scholarships', 0, 0, 0, 'Canada Graduate Scholarship - Masters (CGSM)', 'Bourses d''études supérieures du Canada', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (131, NULL, 'Partnerships Programs', 0, 0, 0, 'Business-Led Networks of Centres of Excellence program', 'Programme des réseaux de centres d''excellence dirigés par l''entreprise', NULL, 0, 0, 7);
INSERT INTO FUNDING_OPPORTUNITY VALUES (132, NULL, 'Partnerships Programs', 0, 0, 0, 'International Knowledge Translation Platforms initiative (IKTP)', 'Initiative de soutien international pour le transfert des connaissances (SITC)', NULL, 0, 0, 7);
INSERT INTO FUNDING_OPPORTUNITY VALUES (133, NULL, 'Partnerships Programs', 0, 0, 0, 'NCE Knowledge Mobilization (NCE-KM)', 'L''initiative de Mobilisation des connaissances (MC-RCE)', NULL, 0, 0, 7);
INSERT INTO FUNDING_OPPORTUNITY VALUES (134, NULL, 'Partnerships Programs', 0, 0, 0, 'Network for Centers of Excellence', 'Programme des réseaux de centres d''excellence (RCE)', NULL, 0, 0, 7);
INSERT INTO FUNDING_OPPORTUNITY VALUES (135, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Technology Access Centre (TAC)', 'subventions d''établissement de centres d''accès à la technologie', NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY VALUES (136, '1/YR+', NULL, 0, 0, 0, 'Canadian Initiative on social Statistics', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (137, '1/YR+', NULL, 0, 0, 0, 'Digging into Data', 'Au cœur des données numériques', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (138, NULL, 'Partnerships Programs', 0, 0, 0, 'Research Partnerships Renewal Project (RPR)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY VALUES (139, '1/YR for first year; unknown after that', 'Research Grant', 0, 0, 0, 'Frontiers in Research Fund - Stream 1', NULL, NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY VALUES (140, '1/YR in second year; unknown after that', 'Research Grant', 0, 0, 0, 'Frontiers in Research Fund - Stream 2', NULL, NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY VALUES (141, 'Unknown, but likely 1/YR in second year', 'Research Grant', 0, 0, 0, 'Frontiers in Research Fund - Special Calls', NULL, NULL, 0, 0, 11);

--POPULATES FUNDING_OPPORTUNITY AUDITING TABLE AND INSERTS THE CORRESPONDING METADATA INTO REVISION_INFO TABLE
INSERT INTO REVISION_INFO VALUES (5, CONVERT(VARCHAR(19), SYSDATETIME(), 120), 'app-admin');
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (1, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Collaborative Health Research Projects (CHRP) (5640)', NULL, NULL, 0, 0, 1);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (2, 5, 0, NULL, NULL, 0, 0, 0, 'IPPH Urban Housing and Health Trainee Research Awards', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (3, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Chairs in Design Engineering (research and salary)', 'Chaires en génie de la conception', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (4, 5, 0, 'Open', 'Research Grants', 0, 0, 0, 'Unique Initiatives Fund (5860)', 'Fonds d''initiatives uniques', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (5, 5, 0, 'Open', 'Research Grants', 0, 0, 0, 'Chairs for Women in Science and Engineering (CWSE)', 'Programme de chaires pour les femmes en sciences et en génie', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (6, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'CMHC Postdoctoral Fellowships', 'Programme de bourses de recherche sur le logement de la SCHL.', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (7, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'Foreign Study Supplements in Taiwan (FSS-Taiwan) (SIT) (5050)', 'Suppléments pour études à Taïwan', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (8, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'JSPS - Postdoctoral Fellowships Program (JSPSF) (4933)', 'Bourses postdoctorales de la Société japonaise pour la promotion de la science', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (9, 5, 0, 'Open', 'Scholarships', 0, 0, 0, 'Aboriginal Ambassadors in the Natural Sciences and Engineering (AANSE) (6610)', 'Bourse pour ambassadeurs autochtones des sciences naturelles et du génie', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (10, 5, 0, '1/YR', 'Prize', 0, 0, 0, 'Brockhouse Canada Prize (5225)', 'Prix Brockhouse du Canada', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (11, 5, 0, '1/YR', NULL, 0, 0, 0, 'Canadian Institute for Theoretical Astrophysics Support Program (CITA) (5632)', 'Programme d''appui à l''Institut canadien d''astrophysique théorique', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (12, 5, 0, '1/YR', 'Fellowships', 0, 0, 0, 'EWR Steacie Fellowships (Research and Salary) (SMFSA-) (5265)', 'Bourses commémoratives E.W.R. Steacie', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (13, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'GENDER-NET Plus', 'ERA-NET Cofund', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (14, 5, 0, '1/YR', 'Prize', 0, 0, 0, 'Herzberg Canada Gold Medal for Science and Engineering (5300)', 'Médaille d''or Gerhard-Herzberg en sciences et en génie du Canada', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (15, 5, 0, '1/YR', 'Prize', 0, 0, 0, 'John C. Polanyi Award (5735)', 'Prix John-C.-Polanyi du CRSNG', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (16, 5, 0, '1/YR', 'Prize', 0, 0, 0, 'NSERC Award for Science Promotion (NASPI)', 'Prix du CRSNG - Promotion des sciences', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (17, 5, 0, '1/YR', 'Prize', 0, 0, 0, 'NSERC Award for Science Promotion (NASPO) (6780)', 'Prix du CRSNG - Promotion des sciences', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (18, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'PromoScience (5390)', 'Promotion des sciences', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (19, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'PromoScience Supplements (PSC)', NULL, NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (20, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'Science Literacy Week (SLW) (PSSLW)', 'Semaine de la culture scientifique', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (21, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'Science Odyssey Supplements (SOS) (PSSOS)', 'Odyssée des sciences', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (22, 5, 0, NULL, 'Scholarships', 0, 0, 0, 'Student Amassadors (NSA) (MFNSA) (5370)', 'Étudiants ambassadeurs du CRSNG', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (23, 5, 0, 'Open', 'Scholarships', 0, 0, 0, 'Young Innovators (MFNYI)', NULL, NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (24, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Collaborative Research and Development Grants (CRD) (6415)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (25, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Community & College Social Innovation Fund (CCSIF) (6017)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (26, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Engage for Colleges (CARD1) (6006)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (27, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Engage for Universities (EGP) (6430)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (28, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Engage Plus Grants for Colleges (CEGP2) (6015)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (29, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Engage Plus Grants for Universities (EGP2) (6432)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (30, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Experience Awards (previously IUSRA)(USRAI) (6030)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (31, 5, 0, '1+/YR', 'Scholarships', 0, 0, 0, 'Undergraduate Student Research Awards (USRA) (URU) (6862)', NULL, NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (32, 5, 0, '1+/YR', NULL, 0, 0, 0, 'Idea to Innovation (I2I) - (I2IPJ) (6036)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (33, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Industrial Research Chairs (IRC) (6235)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (34, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'Postdoctoral Fellowships (PDF) (6790)', NULL, NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (35, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'Postgraduate Scholarships - Doctoral PGS-D2 (Direct and University) (6798)', NULL, NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (36, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'Postgraduate Scholarships - Doctoral PGS-D3 (Direct and University) (6799)', NULL, NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (37, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Strategic Parnerships - Networks (SPG-N)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (38, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Strategic Partnerships - Projects (SPG-P)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (39, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Applied Research Tools and Instruments Grants (ARTI) (CARTI) (6004)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (40, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Belmont Forum (BFAOR) (5807)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (41, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Belmont Forum (BFBIO) (5808)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (42, 5, 0, '1/Year', 'Scholarships', 0, 0, 0, 'CREATE (6648)', NULL, NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (43, 5, 0, 'Open', NULL, 0, 0, 0, 'DND/NSERC Research Partnership (DNDPJ) (6467)', NULL, NULL, 0, 0, 9);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (44, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Human Frontiers in Science Program (HFSP) (5700)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (45, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Innovation Enhancement Grants - Build (IE) CCIP) (6013)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (46, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Innovation Enhancement Grants - Entry (IE) (CCIPE) (6008)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (47, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Innovation Enhancement Grants - Extend (IE) (CCIPX) (6016)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (48, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'Ship Time (RGPST) (5822)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (49, 5, 0, '1/YR', NULL, 0, 0, 0, 'Strategic Network Grants Program (NETGP) (6070)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (50, 5, 0, '1/YR', NULL, 0, 0, 0, 'Subatomic Physics - Individual (SAPIN) (5840)', 'Programme de subventions à la découverte en physique subatomique', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (51, 5, 0, '1/YR', NULL, 0, 0, 0, 'Synergy Awards (Colleges) CSYN (6477)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (52, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Thematic Resources Support in Mathematics and Statistics (CTRMS)', 'Programme d''appui aux ressources thématiques en mathématiques et en statistique', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (53, 5, 0, '1/YR', NULL, 0, 0, 0, 'Discovery Development Grant (DDG)', NULL, NULL, 0, 0, 9);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (54, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'Discovery Grants - Northern Research Supplement (NRS)', 'Programme de suppléments aux subventions à la découverte en recherche nordique', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (55, 5, 0, '1/YR', NULL, 0, 0, 0, 'Discovery Grants (DG) (RGPIN)', 'Programme de subventions à la découverte', NULL, 0, 0, 9);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (56, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'DND/NSERC Discovery Grant Supplement (DGDND)', 'Supplément aux subventions à la découverte MDN-CRSNG', NULL, 0, 0, 9);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (57, 5, 0, '1/YR', NULL, 0, 0, 0, 'Research Tools and Instruments (RTI)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (58, 5, 0, '1/YR', NULL, 0, 0, 0, 'Subatomic Physics - Projects (SAPPJ) - small and large projects', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (59, 5, 0, '1/YR', NULL, 0, 0, 0, 'Subatomic Physics - Research Tools and Instruments (SAP-RTI Cat. 1)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (60, 5, 0, '1/YR', NULL, 0, 0, 0, 'Subatomic Physics - Research Tools and Instruments (SAP-RTI Cat. 2 & 3)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (61, 5, 0, '1/YR', NULL, 0, 0, 0, 'Subatomic Physics Major Resources Support (SAPMR)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (62, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Connect Grants Level 1 for colleges', 'Subventions Connexion Niveau 1 de College', NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (63, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Connect Grants Level 1 for universities', 'Subventions Connexion Niveau 1 des Universities', NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (64, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Connect Grants Level 2 for colleges', 'Subventions Connexion Niveau 2 de College', NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (65, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Connect Grants Level 2 for universities', 'Subventions Connexion Niveau 2 des Universities', NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (66, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'L''Oréal-UNESCO For Women in Science - NSERC Postdoctoral Fellowship Supplement', 'Supplément du CRSNG et de L''Oréal-UNESCO pour les femmes et la science', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (67, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'STEAM Horizon Awards (6850)', 'Prix Horizon STIAM', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (68, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Discovery Frontiers ) (RGPBB)', 'Frontières de la découverte', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (69, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Discovery Frontiers (RGPDD)', 'Frontières de la découverte', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (70, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Discovery Frontiers (RGPDF)', 'Frontières de la découverte', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (71, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Discovery Frontiers (RGPGR)', 'Frontières de la découverte', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (72, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'Discovery Grants - Accelerator Supplement (DAS)', 'Programme de suppléments d''accélération à la découverte', NULL, 0, 0, 9);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (73, 5, 0, NULL, NULL, 0, 0, 0, 'Science Exposed', 'La preuve par l''image', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (74, 5, 0, NULL, NULL, 0, 0, 0, 'Science, Action!', 'Science, Action!', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (75, 5, 0, NULL, NULL, 0, 0, 0, 'College Special Initiatives (CSI)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (76, 5, 0, '1/Year', 'Fellowships', 0, 0, 0, 'EWR Steacie Fellowships (Research and Salary) (SMFSU) (5265)', 'Bourses commémoratives E.W.R. Steacie', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (77, 5, 0, NULL, 'Industrial Research Chairs (IRCPJ) (6235)', 0, 0, 0, 'IRC', 'professeurs-chercheurs industriels', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (78, 5, 0, NULL, 'Research Grants', 0, 0, 0, 'Industrial Research Chairs (IRCSA) (6235)', 'Subventions de professeurs-chercheurs industriels', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (79, 5, 0, NULL, NULL, 0, 0, 0, 'Parental Leave - Research Grants', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (80, 5, 0, NULL, NULL, 0, 0, 0, 'Parental Leave - Scholarships & Fellowships', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (81, 5, 0, '1/YR', NULL, 0, 0, 0, 'Synergy Awards (Universities) (SYN) (5239)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (82, 5, 0, '2/YR', NULL, 0, 0, 0, 'Canada Research Chairs (CRC)', 'Chaires de recherche du Canada', NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (83, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Connections (HSSFC) (650)', 'Lauréate du prix Connexion', NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (84, 5, 0, '1/YR+', 'Research Grants', 0, 0, 0, 'Knowledge Synthesis Grant (872)', 'Subventions de synthèse des connaissances', NULL, 0, 0, 12);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (85, 5, 0, '1/YR', NULL, 0, 0, 0, 'Canada 150 Research Chairs Program', 'Chaires de recherche Canada 150', NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (86, 5, 0, '1/YR', NULL, 0, 0, 0, 'Canada Excellence Research Chairs (CERC)', 'Chaires d''excellence en recherche du Canada', NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (87, 5, 0, '1/YR', NULL, 0, 0, 0, 'Canada First Research Excellence Fund (CFREF)', 'Fonds d''excellence en recherche Apogée Canada', NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (88, 5, 0, '1/YR', 'Prize', 0, 0, 0, 'Impact Awards - Connection (780)', 'Prix Impacts du CRSH Prix Connexion', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (89, 5, 0, '1/YR', 'Prize', 0, 0, 0, 'Impact Awards - Gold Medal (758)', 'Prix Impacts du CRSH Médaille d''or', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (90, 5, 0, '1/YR', 'Prize', 0, 0, 0, 'Impact Awards - Insight (781)', 'Prix Impacts du CRSH Prix Savoir', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (91, 5, 0, '1/YR', 'Prize', 0, 0, 0, 'Impact Awards - Partnership 9782)', 'Prix Impacts du CRSH Prix Partenariat', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (92, 5, 0, '1/YR', 'Prize', 0, 0, 0, 'Impact Awards - Talent (783)', 'Prix Impacts du CRSH Prix Talent', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (93, 5, 0, '1/Year', NULL, 0, 0, 0, 'Indigenous Research Capacity and Reconciliation — Connection Grants', 'Appel à propositions spécial pour l''attribution des subventions Connexion - Capacité de recherche autochtone et réconciliation', NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (94, 5, 0, '1/YR', 'Research Grants', 0, 0, 0, 'Insight Development Grants (430)', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (95, 5, 0, '1/YR', NULL, 0, 0, 0, 'Nelson Mandela', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (96, 5, 0, '1/YR+', 'Research Grant', 0, 0, 0, 'SSHRC Institutional Grant (633)', 'Subventions institutionnelles du CRSH', NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (97, 5, 0, '1/Year', 'Prize', 0, 0, 0, 'Story Tellers', 'J''ai une histoire à raconter', NULL, 0, 0, 14);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (98, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'Bora Laskin National Fellowship (754)', 'Bourse canadienne Bora-Laskin', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (99, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'Jules and Gabrielle Léger (759)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (100, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'Queen''s Fellowship (220 or 321)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (101, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'Aileen D. Ross (230)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (102, 5, 0, '1/YR', 'Internships', 0, 0, 0, 'Mitacs Elevate', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (103, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Aid to Scholarly Journals (651)', 'Aide aux revues savantes', NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (104, 5, 0, '1/YR', 'Fellowships', 0, 0, 0, 'Centre for International Governance Innovation (CIGI)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (105, 5, 0, '1/YR', 'Fellowships', 0, 0, 0, 'CMHC Housing research Training Awards', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (106, 5, 0, '1+/YR', NULL, 0, 0, 0, 'Connection Grants (611)', 'Subventions Connections', NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (107, 5, 0, 'Open', NULL, 0, 0, 0, 'Department of National Defense Research Initiative (877)', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (108, 5, 0, '1/YR', 'Scholarship', 0, 0, 0, 'Doctoral Awards - CGS; Direct; National (752)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (109, 5, 0, '1+/Yr', 'Research Grants', 0, 0, 0, 'Insight Grants (435)', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (110, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Partnership Development Grants (890)', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (111, 5, 0, '1+/YR', 'Partnerships Programs', 0, 0, 0, 'Partnership Engage Grant', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (112, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Partnership Grants - Stage 1', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (113, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Partnership Grants - Stage 2', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (114, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'Postdoctoral Fellowships (756)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (115, 5, 0, 'Open', NULL, 0, 0, 0, 'Sports Participation Research Initative (862)', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (116, 5, 0, 'Open', NULL, 0, 0, 0, 'Parental Leave - Scholarships & Fellowships (SSHRC) (769)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (117, 5, 0, 'Open', NULL, 0, 0, 0, 'Parental Leave - Scholarships and Fellowships through grants (SSHRC)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (118, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Parliamentary Internship Program (750)', 'Programme de stage parlementaire', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (119, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Queen Elizabeth (774)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (120, 5, 0, '1/YR', NULL, 0, 0, 0, 'Special Initiatives Fund For Research Support And Collaboration', NULL, NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (121, 5, 0, '1/YR', NULL, 0, 0, 0, 'Research Support Fund (RSF)', NULL, NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (122, 5, 0, NULL, 'Partnerships Programs', 0, 0, 0, 'CECR Centres of Excellence for Commercialization and Research', ' Programme des centres d''excellence en commercialisation et en recherche', NULL, 0, 0, 7);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (123, 5, 0, '1+/YR', 'Scholarships', 0, 0, 0, 'Canada Graduate Scholarships Michael Smith Foreign Study Supplements (MSFSS)', 'Programme de bourses d''études supérieures du Canada - Suppléments pour études à l''étranger Michael-Smith', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (124, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Applied Research and Development Grants - Colleges (ARD)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (125, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'College - University Idea to Innovation Grants (CU-I2I)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (126, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Industrial Research Chairs for Colleges Grants (IRCC)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (127, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'Alice Wilson', 'Alice Wilson', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (128, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'Banting Postdoctoral Fellowships', 'Bourses postdoctorales Banting', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (129, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'Vanier', NULL, NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (130, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'Canada Graduate Scholarship - Masters (CGSM)', 'Bourses d''études supérieures du Canada', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (131, 5, 0, NULL, 'Partnerships Programs', 0, 0, 0, 'Business-Led Networks of Centres of Excellence program', 'Programme des réseaux de centres d''excellence dirigés par l''entreprise', NULL, 0, 0, 7);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (132, 5, 0, NULL, 'Partnerships Programs', 0, 0, 0, 'International Knowledge Translation Platforms initiative (IKTP)', 'Initiative de soutien international pour le transfert des connaissances (SITC)', NULL, 0, 0, 7);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (133, 5, 0, NULL, 'Partnerships Programs', 0, 0, 0, 'NCE Knowledge Mobilization (NCE-KM)', 'L''initiative de Mobilisation des connaissances (MC-RCE)', NULL, 0, 0, 7);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (134, 5, 0, NULL, 'Partnerships Programs', 0, 0, 0, 'Network for Centers of Excellence', 'Programme des réseaux de centres d''excellence (RCE)', NULL, 0, 0, 7);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (135, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Technology Access Centre (TAC)', 'subventions d''établissement de centres d''accès à la technologie', NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (136, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Canadian Initiative on social Statistics', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (137, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Digging into Data', 'Au cœur des données numériques', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (138, 5, 0, NULL, 'Partnerships Programs', 0, 0, 0, 'Research Partnerships Renewal Project (RPR)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (139, 5, 0, '1/YR for first year; unknown after that', 'Research Grant', 0, 0, 0, 'Frontiers in Research Fund - Stream 1', NULL, NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (140, 5, 0, '1/YR in second year; unknown after that', 'Research Grant', 0, 0, 0, 'Frontiers in Research Fund - Stream 2', NULL, NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (141, 5, 0, 'Unknown, but likely 1/YR in second year', 'Research Grant', 0, 0, 0, 'Frontiers in Research Fund - Special Calls', NULL, NULL, 0, 0, 11);