--POPULATES ROLE TABLE
INSERT INTO ROLE VALUES(NEXT VALUE FOR SEQ_ROLE, 'Program Lead', 'Responsable de Programme');
INSERT INTO ROLE VALUES(NEXT VALUE FOR SEQ_ROLE, 'Program Officer', 'Agent de Programme');

--POPULATES ROLE AUDITING TABLE AND INSERTS THE CORRESPONDING METADATA INTO REVISION_INFO TABLE
INSERT INTO REVISION_INFO VALUES (1, CONVERT(VARCHAR(19), SYSDATETIME(), 120), 'app-admim');
INSERT INTO ROLE_HISTORY VALUES (1, 1, 0, 'Program Lead', 'Responsable de Programme');
INSERT INTO ROLE_HISTORY VALUES (2, 1, 0, 'Program Officer', 'Agent de Programme');

--POPULATES AGENCY TABLE
INSERT INTO AGENCY VALUES (NEXT VALUE FOR SEQ_AGENCY, 'SSHRC', 'CRSN', 'Social Sciences and Humanities Research Council', 'Conseil de Recherches en Sciences Humaines');
INSERT INTO AGENCY VALUES (NEXT VALUE FOR SEQ_AGENCY, 'NSERC', 'CRSNG', 'Natural Sciences and Engineering Research Council', 'Conseil de Recherches en Sciences Naturelles et en Génie');
INSERT INTO AGENCY VALUES (NEXT VALUE FOR SEQ_AGENCY, 'CIHR', 'IRSC', 'Canadian Institutes of Health Research', 'Instituts de Recherche en Santé');

--POPULATES AGENCY AUDITING TABLE AND INSERTS THE CORRESPONDING METADATA INTO REVISION_INFO TABLE
INSERT INTO REVISION_INFO VALUES (2, CONVERT(VARCHAR(19), SYSDATETIME(), 120), 'app-admin');
INSERT INTO AGENCY_HISTORY VALUES (1, 2, 0, 'SSHRC', 'CRSN', 'Social Sciences and Humanities Research Council', 'Conseil de Recherches en Sciences Humaines');
INSERT INTO AGENCY_HISTORY VALUES (2, 2, 0, 'NSERC', 'CRSNG', 'Natural Sciences and Engineering Research Council', 'Conseil de Recherches en Sciences Naturelles et en Génie');
INSERT INTO AGENCY_HISTORY VALUES (3, 2, 0, 'CIHR', 'IRSC', 'Canadian Institutes of Health Research', 'Instituts de Recherche en Santé');

-- POPULTATES GRANTING_SYSTEM TABLE
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'RP1', 'Research Portal', 'Portail de Recherche');
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'CRM', 'CRM', 'CRM');
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'SSHRC Online', 'SSHRC Online', 'SSHRC Online');
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'AMIS', 'AMIS', 'AMIS');
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'NSERC Online', 'NSERC Online', 'NSERC Online');
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'NAMIS', 'NAMIS', 'NAMIS');
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'CIMS', 'Corporate Inventory Management System', 'Corporate Inventory Management System');
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'ResearchNet', 'ResearchNet', 'ResearchNet');
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'Convergence', 'Convergence', 'Convergence');
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'SP Secure Upload', 'SharePoint Secure Upload', 'Téléchargement Sécurisé SharePoint');
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'SP Review', 'SharePoint Review', 'Examen de SharePoint');
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'N/A', 'N/A', 'N/A');

--POPULATES GRANTING_SYSTEM AUDITING TABLE AND INSERTS THE CORRESPONDING METADATA INTO REVISION_INFO TABLE
INSERT INTO REVISION_INFO VALUES (3, CONVERT(VARCHAR(19), SYSDATETIME(), 120), 'app-admin');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (1, 3, 0, 'RP1', 'Research Portal', 'Portail de Recherche');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (2, 3, 0, 'CRM', 'CRM', 'CRM');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (3, 3, 0, 'SSHRC Online', 'SSHRC Online', 'SSHRC Online');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (4, 3, 0, 'AMIS', 'AMIS', 'AMIS');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (5, 3, 0, 'NSERC Online', 'NSERC Online', 'NSERC Online');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (6, 3, 0, 'NAMIS', 'NAMIS', 'NAMIS');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (7, 3, 0, 'CIMS', 'Corporate Inventory Management System', 'Corporate Inventory Management System');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (8, 3, 0, 'ResearchNet', 'ResearchNet', 'ResearchNet');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (9, 3, 0, 'Convergence', 'Convergence', 'Convergence');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (10, 3, 0, 'SP Secure Upload', 'SharePoint Secure Upload', 'Téléchargement Sécurisé SharePoint');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (11, 3, 0, 'SP Review', 'SharePoint Review', 'Examen de SharePoint');
INSERT INTO GRANTING_SYSTEM_HISTORY VALUES (12, 3, 0, 'N/A', 'N/A', 'N/A');

--POPULATES GRATING_STAGE TABLE
INSERT INTO GRANTING_STAGE VALUES (NEXT VALUE FOR SEQ_GRANTING_STAGE, 'ADMIN', 'ADMIN');
INSERT INTO GRANTING_STAGE VALUES (NEXT VALUE FOR SEQ_GRANTING_STAGE, 'APPLY', 'APPLY');
INSERT INTO GRANTING_STAGE VALUES (NEXT VALUE FOR SEQ_GRANTING_STAGE, 'ASSESS', 'ASSESS');
INSERT INTO GRANTING_STAGE VALUES (NEXT VALUE FOR SEQ_GRANTING_STAGE, 'AWARD', 'AWARD');
INSERT INTO GRANTING_STAGE VALUES (NEXT VALUE FOR SEQ_GRANTING_STAGE, 'AQUIT', 'AQUIT');

--POPULATES FISCAL_YEAR TABLE
INSERT INTO FISCAL_YEAR VALUES (NEXT VALUE FOR SEQ_FISCAL_YEAR, 2017);
INSERT INTO FISCAL_YEAR VALUES (NEXT VALUE FOR SEQ_FISCAL_YEAR, 2018);
INSERT INTO FISCAL_YEAR VALUES (NEXT VALUE FOR SEQ_FISCAL_YEAR, 2019);
INSERT INTO FISCAL_YEAR VALUES (NEXT VALUE FOR SEQ_FISCAL_YEAR, 2020);

--POPULATES BUSINESS_UNIT TABLE
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID,DISTRIBUTION) VALUES (NEXT VALUE FOR SEQ_BUSINESS_UNIT, 'MCT', 'FR MCT', 'MCT', 'MCT', 3, 'rpp@nserc-crsng.gc.ca');
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID,DISTRIBUTION) VALUES (NEXT VALUE FOR SEQ_BUSINESS_UNIT, 'EER', 'FR EER', 'EER', 'EER', 2, 'rpp@nserc-crsng.gc.ca');
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (NEXT VALUE FOR SEQ_BUSINESS_UNIT, 'ICSP', 'FR ICSP', 'ICSP', 'ICSP', 2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (NEXT VALUE FOR SEQ_BUSINESS_UNIT, 'SF', 'FR SF', 'SF', 'SF', 2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (NEXT VALUE FOR SEQ_BUSINESS_UNIT, 'MEPS', 'FR MEPS', 'MEPS', 'MEPS', 2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID,DISTRIBUTION) VALUES (NEXT VALUE FOR SEQ_BUSINESS_UNIT, 'CCPP', 'FR CCPP', 'CCPP', 'CCPP', 2, 'i2i@nserc-crsng.gc.ca');
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID,DISTRIBUTION) VALUES (NEXT VALUE FOR SEQ_BUSINESS_UNIT, 'NCE', 'FR NCE', 'NCE', 'NCE', 3, 'info@nce-rce.gc.ca, alex.pigeon@nce-rce.gc.ca');
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID,DISTRIBUTION) VALUES (NEXT VALUE FOR SEQ_BUSINESS_UNIT, 'RP', 'FR RP', 'RP', 'RP', 2, 'alliance@nserc-crsng.gc.ca');
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID) VALUES (NEXT VALUE FOR SEQ_BUSINESS_UNIT, 'ELS', 'FR ELS', 'ELS', 'ELS', 2);
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID,DISTRIBUTION) VALUES (NEXT VALUE FOR SEQ_BUSINESS_UNIT, 'RGPD', 'FR RGPD', 'RGPD','RGPD', 1, 'partnershipgrants@sshrc-crsh.gc.ca, partnershipdevelopment@sshrc-crsh.gc.ca, colleges@nserc-crsng.gc.ca, connection@sshrc-crsh.gc.ca, partnershipengagegrants@sshrc-crsh.gc.ca');
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID,DISTRIBUTION) VALUES (NEXT VALUE FOR SEQ_BUSINESS_UNIT, 'TIPS', 'FR TIPS', 'TIPS','TIPS', 1, 'information@chairs-chaires.gc.ca');
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID,DISTRIBUTION) VALUES (NEXT VALUE FOR SEQ_BUSINESS_UNIT, 'FCD', 'FR FCD', 'FCD','FCD', 1, 'KSG-SSC@sshrc-crsh.gc.ca');
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID,DISTRIBUTION) VALUES (NEXT VALUE FOR SEQ_BUSINESS_UNIT, 'RTP', 'FR RTP', 'RTP','RTP', 1, 'fellowships@sshrc-crsh.gc.ca');
INSERT INTO BUSINESS_UNIT (ID,NAME_EN,NAME_FR,ACRONYM_EN,ACRONYM_FR,AGENCY_ID,DISTRIBUTION) VALUES (NEXT VALUE FOR SEQ_BUSINESS_UNIT, 'Comms', 'FR Comms', 'COMMS','COMMS', 1, 'storytellers@sshrc-crsh.gc.ca');

--POPULATES BUSINESS_UNIT AUDITING TABLE AND INSERTS THE CORRESPONDING METADATA INTO REVISION_INFO TABLE
INSERT INTO REVISION_INFO VALUES (4, CONVERT(VARCHAR(19), SYSDATETIME(), 120), 'app-admin');
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (1, 4, 0, 'MCT', 'FR MCT', 'MCT', 'MCT', 3, 'rpp@nserc-crsng.gc.ca');
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (2, 4, 0, 'EER', 'FR EER', 'EER', 'EER', 2, 'rpp@nserc-crsng.gc.ca');
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (3, 4, 0, 'ICSP', 'FR ICSP', 'ICSP', 'ICSP', 2, NULL);
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (4, 4, 0, 'SF', 'FR SF','SF', 'SF', 2, NULL);
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (5, 4, 0, 'MEPS', 'FR MEPS', 'MEPS', 'MEPS', 2, NULL);
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (6, 4, 0, 'CCPP', 'FR CCPP', 'CCPP', 'CCPP', 2, 'i2i@nserc-crsng.gc.ca');
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (7, 4, 0, 'NCE', 'FR NCE', 'NCE', 'NCE', 3, 'info@nce-rce.gc.ca, alex.pigeon@nce-rce.gc.ca');
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (8, 4, 0, 'RP', 'FR RP', 'RP', 'RP', 2, 'alliance@nserc-crsng.gc.ca');
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (9, 4, 0, 'ELS', 'FR ELS', 'ELS', 'ELS', 2, NULL);
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (10, 4, 0, 'RGPD', 'FR RGPD', 'RGPD', 'RGPD', 1, 'partnershipgrants@sshrc-crsh.gc.ca, partnershipdevelopment@sshrc-crsh.gc.ca, colleges@nserc-crsng.gc.ca, connection@sshrc-crsh.gc.ca, partnershipengagegrants@sshrc-crsh.gc.ca');
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (11, 4, 0, 'TIPS', 'FR TIPS', 'TIPS', 'TIPS', 1, 'information@chairs-chaires.gc.ca');
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (12, 4, 0, 'FCD', 'FR FCD', 'FCD', 'FCD', 1, 'KSG-SSC@sshrc-crsh.gc.ca');
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (13, 4, 0, 'RTP', 'FR RTP', 'RTP', 'RTP', 1, 'fellowships@sshrc-crsh.gc.ca');
INSERT INTO BUSINESS_UNIT_HISTORY VALUES (14, 4, 0, 'Comms', 'FR Comms', 'COMMS', 'COMMS', 1, 'storytellers@sshrc-crsh.gc.ca');

--POPULATES FUNDING_OPPORTUNITY TABLE
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Collaborative Health Research Projects (CHRP) (5640)', NULL, NULL, 0, 0, 1);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, NULL, NULL, 0, 0, 0, 'IPPH Urban Housing and Health Trainee Research Awards', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Chairs in Design Engineering (research and salary)', 'Chaires en génie de la conception', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', 'Research Grants', 0, 0, 0, 'Unique Initiatives Fund (5860)', 'Fonds d''initiatives uniques', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', 'Research Grants', 0, 0, 0, 'Chairs for Women in Science and Engineering (CWSE)', 'Programme de chaires pour les femmes en sciences et en génie', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Scholarships', 0, 0, 0, 'CMHC Postdoctoral Fellowships', 'Programme de bourses de recherche sur le logement de la SCHL.', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Scholarships', 0, 0, 0, 'Foreign Study Supplements in Taiwan (FSS-Taiwan) (SIT) (5050)', 'Suppléments pour études à Taïwan', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Scholarships', 0, 0, 0, 'JSPS - Postdoctoral Fellowships Program (JSPSF) (4933)', 'Bourses postdoctorales de la Société japonaise pour la promotion de la science', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', 'Scholarships', 0, 0, 0, 'Aboriginal Ambassadors in the Natural Sciences and Engineering (AANSE) (6610)', 'Bourse pour ambassadeurs autochtones des sciences naturelles et du génie', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Prize', 0, 0, 0, 'Brockhouse Canada Prize (5225)', 'Prix Brockhouse du Canada', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', NULL, 0, 0, 0, 'Canadian Institute for Theoretical Astrophysics Support Program (CITA) (5632)', 'Programme d''appui à l''Institut canadien d''astrophysique théorique', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Fellowships', 0, 0, 0, 'EWR Steacie Fellowships (Research and Salary) (SMFSA-) (5265)', 'Bourses commémoratives E.W.R. Steacie', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Scholarships', 0, 0, 0, 'GENDER-NET Plus', 'ERA-NET Cofund', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Prize', 0, 0, 0, 'Herzberg Canada Gold Medal for Science and Engineering (5300)', 'Médaille d''or Gerhard-Herzberg en sciences et en génie du Canada', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Prize', 0, 0, 0, 'John C. Polanyi Award (5735)', 'Prix John-C.-Polanyi du CRSNG', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Prize', 0, 0, 0, 'NSERC Award for Science Promotion (NASPI)', 'Prix du CRSNG - Promotion des sciences', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Prize', 0, 0, 0, 'NSERC Award for Science Promotion (NASPO) (6780)', 'Prix du CRSNG - Promotion des sciences', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Scholarships', 0, 0, 0, 'PromoScience (5390)', 'Promotion des sciences', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Supplement', 0, 0, 0, 'PromoScience Supplements (PSC)', NULL, NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Supplement', 0, 0, 0, 'Science Literacy Week (SLW) (PSSLW)', 'Semaine de la culture scientifique', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Supplement', 0, 0, 0, 'Science Odyssey Supplements (SOS) (PSSOS)', 'Odyssée des sciences', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, NULL, 'Scholarships', 0, 0, 0, 'Student Amassadors (NSA) (MFNSA) (5370)', 'Étudiants ambassadeurs du CRSNG', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', 'Scholarships', 0, 0, 0, 'Young Innovators (MFNYI)', NULL, NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', 'Partnerships Programs', 0, 0, 0, 'Collaborative Research and Development Grants (CRD) (6415)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Community & College Social Innovation Fund (CCSIF) (6017)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', 'Partnerships Programs', 0, 0, 0, 'Engage for Colleges (CARD1) (6006)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', 'Partnerships Programs', 0, 0, 0, 'Engage for Universities (EGP) (6430)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', 'Partnerships Programs', 0, 0, 0, 'Engage Plus Grants for Colleges (CEGP2) (6015)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', 'Partnerships Programs', 0, 0, 0, 'Engage Plus Grants for Universities (EGP2) (6432)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', 'Partnerships Programs', 0, 0, 0, 'Experience Awards (previously IUSRA)(USRAI) (6030)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1+/YR', 'Scholarships', 0, 0, 0, 'Undergraduate Student Research Awards (USRA) (URU) (6862)', NULL, NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1+/YR', NULL, 0, 0, 0, 'Idea to Innovation (I2I) - (I2IPJ) (6036)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', 'Partnerships Programs', 0, 0, 0, 'Industrial Research Chairs (IRC) (6235)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Scholarships', 0, 0, 0, 'Postdoctoral Fellowships (PDF) (6790)', NULL, NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Scholarships', 0, 0, 0, 'Postgraduate Scholarships - Doctoral PGS-D2 (Direct and University) (6798)', NULL, NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Scholarships', 0, 0, 0, 'Postgraduate Scholarships - Doctoral PGS-D3 (Direct and University) (6799)', NULL, NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Strategic Parnerships - Networks (SPG-N)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Strategic Partnerships - Projects (SPG-P)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Applied Research Tools and Instruments Grants (ARTI) (CARTI) (6004)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR+', NULL, 0, 0, 0, 'Belmont Forum (BFAOR) (5807)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR+', NULL, 0, 0, 0, 'Belmont Forum (BFBIO) (5808)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/Year', 'Scholarships', 0, 0, 0, 'CREATE (6648)', NULL, NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', NULL, 0, 0, 0, 'DND/NSERC Research Partnership (DNDPJ) (6467)', NULL, NULL, 0, 0, 9);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR+', NULL, 0, 0, 0, 'Human Frontiers in Science Program (HFSP) (5700)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Innovation Enhancement Grants - Build (IE) CCIP) (6013)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Innovation Enhancement Grants - Entry (IE) (CCIPE) (6008)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Innovation Enhancement Grants - Extend (IE) (CCIPX) (6016)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Supplement', 0, 0, 0, 'Ship Time (RGPST) (5822)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', NULL, 0, 0, 0, 'Strategic Network Grants Program (NETGP) (6070)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', NULL, 0, 0, 0, 'Subatomic Physics - Individual (SAPIN) (5840)', 'Programme de subventions à la découverte en physique subatomique', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', NULL, 0, 0, 0, 'Synergy Awards (Colleges) CSYN (6477)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR+', NULL, 0, 0, 0, 'Thematic Resources Support in Mathematics and Statistics (CTRMS)', 'Programme d''appui aux ressources thématiques en mathématiques et en statistique', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', NULL, 0, 0, 0, 'Discovery Development Grant (DDG)', NULL, NULL, 0, 0, 9);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Supplement', 0, 0, 0, 'Discovery Grants - Northern Research Supplement (NRS)', 'Programme de suppléments aux subventions à la découverte en recherche nordique', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', NULL, 0, 0, 0, 'Discovery Grants (DG) (RGPIN)', 'Programme de subventions à la découverte', NULL, 0, 0, 9);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Supplement', 0, 0, 0, 'DND/NSERC Discovery Grant Supplement (DGDND)', 'Supplément aux subventions à la découverte MDN-CRSNG', NULL, 0, 0, 9);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', NULL, 0, 0, 0, 'Research Tools and Instruments (RTI)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', NULL, 0, 0, 0, 'Subatomic Physics - Projects (SAPPJ) - small and large projects', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', NULL, 0, 0, 0, 'Subatomic Physics - Research Tools and Instruments (SAP-RTI Cat. 1)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', NULL, 0, 0, 0, 'Subatomic Physics - Research Tools and Instruments (SAP-RTI Cat. 2 & 3)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', NULL, 0, 0, 0, 'Subatomic Physics Major Resources Support (SAPMR)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', 'Partnerships Programs', 0, 0, 0, 'Connect Grants Level 1 for colleges', 'Subventions Connexion Niveau 1 de College', NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', 'Partnerships Programs', 0, 0, 0, 'Connect Grants Level 1 for universities', 'Subventions Connexion Niveau 1 des Universities', NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', 'Partnerships Programs', 0, 0, 0, 'Connect Grants Level 2 for colleges', 'Subventions Connexion Niveau 2 de College', NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', 'Partnerships Programs', 0, 0, 0, 'Connect Grants Level 2 for universities', 'Subventions Connexion Niveau 2 des Universities', NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Scholarships', 0, 0, 0, 'L''Oréal-UNESCO For Women in Science - NSERC Postdoctoral Fellowship Supplement', 'Supplément du CRSNG et de L''Oréal-UNESCO pour les femmes et la science', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Scholarships', 0, 0, 0, 'STEAM Horizon Awards (6850)', 'Prix Horizon STIAM', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR+', NULL, 0, 0, 0, 'Discovery Frontiers ) (RGPBB)', 'Frontières de la découverte', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR+', NULL, 0, 0, 0, 'Discovery Frontiers (RGPDD)', 'Frontières de la découverte', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR+', NULL, 0, 0, 0, 'Discovery Frontiers (RGPDF)', 'Frontières de la découverte', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR+', NULL, 0, 0, 0, 'Discovery Frontiers (RGPGR)', 'Frontières de la découverte', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Supplement', 0, 0, 0, 'Discovery Grants - Accelerator Supplement (DAS)', 'Programme de suppléments d''accélération à la découverte', NULL, 0, 0, 9);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, NULL, NULL, 0, 0, 0, 'Science Exposed', 'La preuve par l''image', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, NULL, NULL, 0, 0, 0, 'Science, Action!', 'Science, Action!', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, NULL, NULL, 0, 0, 0, 'College Special Initiatives (CSI)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/Year', 'Fellowships', 0, 0, 0, 'EWR Steacie Fellowships (Research and Salary) (SMFSU) (5265)', 'Bourses commémoratives E.W.R. Steacie', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, NULL, 'Industrial Research Chairs (IRCPJ) (6235)', 0, 0, 0, 'IRC', 'professeurs-chercheurs industriels', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, NULL, 'Research Grants', 0, 0, 0, 'Industrial Research Chairs (IRCSA) (6235)', 'Subventions de professeurs-chercheurs industriels', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, NULL, NULL, 0, 0, 0, 'Parental Leave - Research Grants', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, NULL, NULL, 0, 0, 0, 'Parental Leave - Scholarships & Fellowships', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', NULL, 0, 0, 0, 'Synergy Awards (Universities) (SYN) (5239)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '2/YR', NULL, 0, 0, 0, 'Canada Research Chairs (CRC)', 'Chaires de recherche du Canada', NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR+', NULL, 0, 0, 0, 'Connections (HSSFC) (650)', 'Lauréate du prix Connexion', NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR+', 'Research Grants', 0, 0, 0, 'Knowledge Synthesis Grant (872)', 'Subventions de synthèse des connaissances', NULL, 0, 0, 12);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', NULL, 0, 0, 0, 'Canada 150 Research Chairs Program', 'Chaires de recherche Canada 150', NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', NULL, 0, 0, 0, 'Canada Excellence Research Chairs (CERC)', 'Chaires d''excellence en recherche du Canada', NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', NULL, 0, 0, 0, 'Canada First Research Excellence Fund (CFREF)', 'Fonds d''excellence en recherche Apogée Canada', NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Prize', 0, 0, 0, 'Impact Awards - Connection (780)', 'Prix Impacts du CRSH Prix Connexion', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Prize', 0, 0, 0, 'Impact Awards - Gold Medal (758)', 'Prix Impacts du CRSH Médaille d''or', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Prize', 0, 0, 0, 'Impact Awards - Insight (781)', 'Prix Impacts du CRSH Prix Savoir', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Prize', 0, 0, 0, 'Impact Awards - Partnership 9782)', 'Prix Impacts du CRSH Prix Partenariat', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Prize', 0, 0, 0, 'Impact Awards - Talent (783)', 'Prix Impacts du CRSH Prix Talent', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/Year', NULL, 0, 0, 0, 'Indigenous Research Capacity and Reconciliation — Connection Grants', 'Appel à propositions spécial pour l''attribution des subventions Connexion - Capacité de recherche autochtone et réconciliation', NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Research Grants', 0, 0, 0, 'Insight Development Grants (430)', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', NULL, 0, 0, 0, 'Nelson Mandela', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR+', 'Research Grant', 0, 0, 0, 'SSHRC Institutional Grant (633)', 'Subventions institutionnelles du CRSH', NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/Year', 'Prize', 0, 0, 0, 'Story Tellers', 'J''ai une histoire à raconter', NULL, 0, 0, 14);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Supplement', 0, 0, 0, 'Bora Laskin National Fellowship (754)', 'Bourse canadienne Bora-Laskin', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Supplement', 0, 0, 0, 'Jules and Gabrielle Léger (759)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Supplement', 0, 0, 0, 'Queen''s Fellowship (220 or 321)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Supplement', 0, 0, 0, 'Aileen D. Ross (230)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Internships', 0, 0, 0, 'Mitacs Elevate', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR+', NULL, 0, 0, 0, 'Aid to Scholarly Journals (651)', 'Aide aux revues savantes', NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Fellowships', 0, 0, 0, 'Centre for International Governance Innovation (CIGI)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Fellowships', 0, 0, 0, 'CMHC Housing research Training Awards', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1+/YR', NULL, 0, 0, 0, 'Connection Grants (611)', 'Subventions Connections', NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', NULL, 0, 0, 0, 'Department of National Defense Research Initiative (877)', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Scholarship', 0, 0, 0, 'Doctoral Awards - CGS; Direct; National (752)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1+/Yr', 'Research Grants', 0, 0, 0, 'Insight Grants (435)', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Partnership Development Grants (890)', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1+/YR', 'Partnerships Programs', 0, 0, 0, 'Partnership Engage Grant', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Partnership Grants - Stage 1', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Partnership Grants - Stage 2', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Scholarships', 0, 0, 0, 'Postdoctoral Fellowships (756)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', NULL, 0, 0, 0, 'Sports Participation Research Initative (862)', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', NULL, 0, 0, 0, 'Parental Leave - Scholarships & Fellowships (SSHRC) (769)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', NULL, 0, 0, 0, 'Parental Leave - Scholarships and Fellowships through grants (SSHRC)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Parliamentary Internship Program (750)', 'Programme de stage parlementaire', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Queen Elizabeth (774)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', NULL, 0, 0, 0, 'Special Initiatives Fund For Research Support And Collaboration', NULL, NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', NULL, 0, 0, 0, 'Research Support Fund (RSF)', NULL, NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, NULL, 'Partnerships Programs', 0, 0, 0, 'CECR Centres of Excellence for Commercialization and Research', ' Programme des centres d''excellence en commercialisation et en recherche', NULL, 0, 0, 7);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1+/YR', 'Scholarships', 0, 0, 0, 'Canada Graduate Scholarships Michael Smith Foreign Study Supplements (MSFSS)', 'Programme de bourses d''études supérieures du Canada - Suppléments pour études à l''étranger Michael-Smith', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Open', 'Partnerships Programs', 0, 0, 0, 'Applied Research and Development Grants - Colleges (ARD)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Partnerships Programs', 0, 0, 0, 'College - University Idea to Innovation Grants (CU-I2I)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Industrial Research Chairs for Colleges Grants (IRCC)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Supplement', 0, 0, 0, 'Alice Wilson', 'Alice Wilson', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Scholarships', 0, 0, 0, 'Banting Postdoctoral Fellowships', 'Bourses postdoctorales Banting', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Scholarships', 0, 0, 0, 'Vanier', NULL, NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Scholarships', 0, 0, 0, 'Canada Graduate Scholarship - Masters (CGSM)', 'Bourses d''études supérieures du Canada', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, NULL, 'Partnerships Programs', 0, 0, 0, 'Business-Led Networks of Centres of Excellence program', 'Programme des réseaux de centres d''excellence dirigés par l''entreprise', NULL, 0, 0, 7);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, NULL, 'Partnerships Programs', 0, 0, 0, 'International Knowledge Translation Platforms initiative (IKTP)', 'Initiative de soutien international pour le transfert des connaissances (SITC)', NULL, 0, 0, 7);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, NULL, 'Partnerships Programs', 0, 0, 0, 'NCE Knowledge Mobilization (NCE-KM)', 'L''initiative de Mobilisation des connaissances (MC-RCE)', NULL, 0, 0, 7);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, NULL, 'Partnerships Programs', 0, 0, 0, 'Network for Centers of Excellence', 'Programme des réseaux de centres d''excellence (RCE)', NULL, 0, 0, 7);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Technology Access Centre (TAC)', 'subventions d''établissement de centres d''accès à la technologie', NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR+', NULL, 0, 0, 0, 'Canadian Initiative on social Statistics', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR+', NULL, 0, 0, 0, 'Digging into Data', 'Au cœur des données numériques', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, NULL, 'Partnerships Programs', 0, 0, 0, 'Research Partnerships Renewal Project (RPR)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR for first year; unknown after that', 'Research Grant', 0, 0, 0, 'Frontiers in Research Fund - Stream 1', NULL, NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, '1/YR in second year; unknown after that', 'Research Grant', 0, 0, 0, 'Frontiers in Research Fund - Stream 2', NULL, NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY VALUES (NEXT VALUE FOR SEQ_FUNDING_OPPORTUNITY, 'Unknown, but likely 1/YR in second year', 'Research Grant', 0, 0, 0, 'Frontiers in Research Fund - Special Calls', NULL, NULL, 0, 0, 11);

--POPULATES FUNDING_OPPORTUNITY AUDITING TABLE AND INSERTS THE CORRESPONDING METADATA INTO REVISION_INFO TABLE
INSERT INTO REVISION_INFO VALUES (5, CONVERT(VARCHAR(19), SYSDATETIME(), 120), 'app-admin');
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (1, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Collaborative Health Research Projects (CHRP) (5640)', NULL, NULL, 0, 0, 1);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (2, 5, 0, NULL, NULL, 0, 0, 0, 'IPPH Urban Housing and Health Trainee Research Awards', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (3, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Chairs in Design Engineering (research and salary)', 'Chaires en génie de la conception', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (4, 5, 0, 'Open', 'Research Grants', 0, 0, 0, 'Unique Initiatives Fund (5860)', 'Fonds d''initiatives uniques', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (5, 5, 0, 'Open', 'Research Grants', 0, 0, 0, 'Chairs for Women in Science and Engineering (CWSE)', 'Programme de chaires pour les femmes en sciences et en génie', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (6, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'CMHC Postdoctoral Fellowships', 'Programme de bourses de recherche sur le logement de la SCHL.', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (7, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'Foreign Study Supplements in Taiwan (FSS-Taiwan) (SIT) (5050)', 'Suppléments pour études à Taïwan', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (8, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'JSPS - Postdoctoral Fellowships Program (JSPSF) (4933)', 'Bourses postdoctorales de la Société japonaise pour la promotion de la science', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (9, 5, 0, 'Open', 'Scholarships', 0, 0, 0, 'Aboriginal Ambassadors in the Natural Sciences and Engineering (AANSE) (6610)', 'Bourse pour ambassadeurs autochtones des sciences naturelles et du génie', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (10, 5, 0, '1/YR', 'Prize', 0, 0, 0, 'Brockhouse Canada Prize (5225)', 'Prix Brockhouse du Canada', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (11, 5, 0, '1/YR', NULL, 0, 0, 0, 'Canadian Institute for Theoretical Astrophysics Support Program (CITA) (5632)', 'Programme d''appui à l''Institut canadien d''astrophysique théorique', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (12, 5, 0, '1/YR', 'Fellowships', 0, 0, 0, 'EWR Steacie Fellowships (Research and Salary) (SMFSA-) (5265)', 'Bourses commémoratives E.W.R. Steacie', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (13, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'GENDER-NET Plus', 'ERA-NET Cofund', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (14, 5, 0, '1/YR', 'Prize', 0, 0, 0, 'Herzberg Canada Gold Medal for Science and Engineering (5300)', 'Médaille d''or Gerhard-Herzberg en sciences et en génie du Canada', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (15, 5, 0, '1/YR', 'Prize', 0, 0, 0, 'John C. Polanyi Award (5735)', 'Prix John-C.-Polanyi du CRSNG', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (16, 5, 0, '1/YR', 'Prize', 0, 0, 0, 'NSERC Award for Science Promotion (NASPI)', 'Prix du CRSNG - Promotion des sciences', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (17, 5, 0, '1/YR', 'Prize', 0, 0, 0, 'NSERC Award for Science Promotion (NASPO) (6780)', 'Prix du CRSNG - Promotion des sciences', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (18, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'PromoScience (5390)', 'Promotion des sciences', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (19, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'PromoScience Supplements (PSC)', NULL, NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (20, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'Science Literacy Week (SLW) (PSSLW)', 'Semaine de la culture scientifique', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (21, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'Science Odyssey Supplements (SOS) (PSSOS)', 'Odyssée des sciences', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (22, 5, 0, NULL, 'Scholarships', 0, 0, 0, 'Student Amassadors (NSA) (MFNSA) (5370)', 'Étudiants ambassadeurs du CRSNG', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (23, 5, 0, 'Open', 'Scholarships', 0, 0, 0, 'Young Innovators (MFNYI)', NULL, NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (24, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Collaborative Research and Development Grants (CRD) (6415)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (25, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Community & College Social Innovation Fund (CCSIF) (6017)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (26, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Engage for Colleges (CARD1) (6006)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (27, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Engage for Universities (EGP) (6430)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (28, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Engage Plus Grants for Colleges (CEGP2) (6015)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (29, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Engage Plus Grants for Universities (EGP2) (6432)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (30, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Experience Awards (previously IUSRA)(USRAI) (6030)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (31, 5, 0, '1+/YR', 'Scholarships', 0, 0, 0, 'Undergraduate Student Research Awards (USRA) (URU) (6862)', NULL, NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (32, 5, 0, '1+/YR', NULL, 0, 0, 0, 'Idea to Innovation (I2I) - (I2IPJ) (6036)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (33, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Industrial Research Chairs (IRC) (6235)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (34, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'Postdoctoral Fellowships (PDF) (6790)', NULL, NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (35, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'Postgraduate Scholarships - Doctoral PGS-D2 (Direct and University) (6798)', NULL, NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (36, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'Postgraduate Scholarships - Doctoral PGS-D3 (Direct and University) (6799)', NULL, NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (37, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Strategic Parnerships - Networks (SPG-N)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (38, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Strategic Partnerships - Projects (SPG-P)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (39, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Applied Research Tools and Instruments Grants (ARTI) (CARTI) (6004)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (40, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Belmont Forum (BFAOR) (5807)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (41, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Belmont Forum (BFBIO) (5808)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (42, 5, 0, '1/Year', 'Scholarships', 0, 0, 0, 'CREATE (6648)', NULL, NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (43, 5, 0, 'Open', NULL, 0, 0, 0, 'DND/NSERC Research Partnership (DNDPJ) (6467)', NULL, NULL, 0, 0, 9);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (44, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Human Frontiers in Science Program (HFSP) (5700)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (45, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Innovation Enhancement Grants - Build (IE) CCIP) (6013)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (46, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Innovation Enhancement Grants - Entry (IE) (CCIPE) (6008)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (47, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Innovation Enhancement Grants - Extend (IE) (CCIPX) (6016)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (48, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'Ship Time (RGPST) (5822)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (49, 5, 0, '1/YR', NULL, 0, 0, 0, 'Strategic Network Grants Program (NETGP) (6070)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (50, 5, 0, '1/YR', NULL, 0, 0, 0, 'Subatomic Physics - Individual (SAPIN) (5840)', 'Programme de subventions à la découverte en physique subatomique', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (51, 5, 0, '1/YR', NULL, 0, 0, 0, 'Synergy Awards (Colleges) CSYN (6477)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (52, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Thematic Resources Support in Mathematics and Statistics (CTRMS)', 'Programme d''appui aux ressources thématiques en mathématiques et en statistique', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (53, 5, 0, '1/YR', NULL, 0, 0, 0, 'Discovery Development Grant (DDG)', NULL, NULL, 0, 0, 9);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (54, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'Discovery Grants - Northern Research Supplement (NRS)', 'Programme de suppléments aux subventions à la découverte en recherche nordique', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (55, 5, 0, '1/YR', NULL, 0, 0, 0, 'Discovery Grants (DG) (RGPIN)', 'Programme de subventions à la découverte', NULL, 0, 0, 9);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (56, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'DND/NSERC Discovery Grant Supplement (DGDND)', 'Supplément aux subventions à la découverte MDN-CRSNG', NULL, 0, 0, 9);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (57, 5, 0, '1/YR', NULL, 0, 0, 0, 'Research Tools and Instruments (RTI)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (58, 5, 0, '1/YR', NULL, 0, 0, 0, 'Subatomic Physics - Projects (SAPPJ) - small and large projects', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (59, 5, 0, '1/YR', NULL, 0, 0, 0, 'Subatomic Physics - Research Tools and Instruments (SAP-RTI Cat. 1)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (60, 5, 0, '1/YR', NULL, 0, 0, 0, 'Subatomic Physics - Research Tools and Instruments (SAP-RTI Cat. 2 & 3)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (61, 5, 0, '1/YR', NULL, 0, 0, 0, 'Subatomic Physics Major Resources Support (SAPMR)', NULL, NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (62, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Connect Grants Level 1 for colleges', 'Subventions Connexion Niveau 1 de College', NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (63, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Connect Grants Level 1 for universities', 'Subventions Connexion Niveau 1 des Universities', NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (64, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Connect Grants Level 2 for colleges', 'Subventions Connexion Niveau 2 de College', NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (65, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Connect Grants Level 2 for universities', 'Subventions Connexion Niveau 2 des Universities', NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (66, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'L''Oréal-UNESCO For Women in Science - NSERC Postdoctoral Fellowship Supplement', 'Supplément du CRSNG et de L''Oréal-UNESCO pour les femmes et la science', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (67, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'STEAM Horizon Awards (6850)', 'Prix Horizon STIAM', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (68, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Discovery Frontiers ) (RGPBB)', 'Frontières de la découverte', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (69, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Discovery Frontiers (RGPDD)', 'Frontières de la découverte', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (70, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Discovery Frontiers (RGPDF)', 'Frontières de la découverte', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (71, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Discovery Frontiers (RGPGR)', 'Frontières de la découverte', NULL, 0, 0, 5);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (72, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'Discovery Grants - Accelerator Supplement (DAS)', 'Programme de suppléments d''accélération à la découverte', NULL, 0, 0, 9);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (73, 5, 0, NULL, NULL, 0, 0, 0, 'Science Exposed', 'La preuve par l''image', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (74, 5, 0, NULL, NULL, 0, 0, 0, 'Science, Action!', 'Science, Action!', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (75, 5, 0, NULL, NULL, 0, 0, 0, 'College Special Initiatives (CSI)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (76, 5, 0, '1/Year', 'Fellowships', 0, 0, 0, 'EWR Steacie Fellowships (Research and Salary) (SMFSU) (5265)', 'Bourses commémoratives E.W.R. Steacie', NULL, 0, 0, 3);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (77, 5, 0, NULL, 'Industrial Research Chairs (IRCPJ) (6235)', 0, 0, 0, 'IRC', 'professeurs-chercheurs industriels', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (78, 5, 0, NULL, 'Research Grants', 0, 0, 0, 'Industrial Research Chairs (IRCSA) (6235)', 'Subventions de professeurs-chercheurs industriels', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (79, 5, 0, NULL, NULL, 0, 0, 0, 'Parental Leave - Research Grants', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (80, 5, 0, NULL, NULL, 0, 0, 0, 'Parental Leave - Scholarships & Fellowships', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (81, 5, 0, '1/YR', NULL, 0, 0, 0, 'Synergy Awards (Universities) (SYN) (5239)', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (82, 5, 0, '2/YR', NULL, 0, 0, 0, 'Canada Research Chairs (CRC)', 'Chaires de recherche du Canada', NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (83, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Connections (HSSFC) (650)', 'Lauréate du prix Connexion', NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (84, 5, 0, '1/YR+', 'Research Grants', 0, 0, 0, 'Knowledge Synthesis Grant (872)', 'Subventions de synthèse des connaissances', NULL, 0, 0, 12);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (85, 5, 0, '1/YR', NULL, 0, 0, 0, 'Canada 150 Research Chairs Program', 'Chaires de recherche Canada 150', NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (86, 5, 0, '1/YR', NULL, 0, 0, 0, 'Canada Excellence Research Chairs (CERC)', 'Chaires d''excellence en recherche du Canada', NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (87, 5, 0, '1/YR', NULL, 0, 0, 0, 'Canada First Research Excellence Fund (CFREF)', 'Fonds d''excellence en recherche Apogée Canada', NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (88, 5, 0, '1/YR', 'Prize', 0, 0, 0, 'Impact Awards - Connection (780)', 'Prix Impacts du CRSH Prix Connexion', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (89, 5, 0, '1/YR', 'Prize', 0, 0, 0, 'Impact Awards - Gold Medal (758)', 'Prix Impacts du CRSH Médaille d''or', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (90, 5, 0, '1/YR', 'Prize', 0, 0, 0, 'Impact Awards - Insight (781)', 'Prix Impacts du CRSH Prix Savoir', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (91, 5, 0, '1/YR', 'Prize', 0, 0, 0, 'Impact Awards - Partnership 9782)', 'Prix Impacts du CRSH Prix Partenariat', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (92, 5, 0, '1/YR', 'Prize', 0, 0, 0, 'Impact Awards - Talent (783)', 'Prix Impacts du CRSH Prix Talent', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (93, 5, 0, '1/Year', NULL, 0, 0, 0, 'Indigenous Research Capacity and Reconciliation — Connection Grants', 'Appel à propositions spécial pour l''attribution des subventions Connexion - Capacité de recherche autochtone et réconciliation', NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (94, 5, 0, '1/YR', 'Research Grants', 0, 0, 0, 'Insight Development Grants (430)', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (95, 5, 0, '1/YR', NULL, 0, 0, 0, 'Nelson Mandela', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (96, 5, 0, '1/YR+', 'Research Grant', 0, 0, 0, 'SSHRC Institutional Grant (633)', 'Subventions institutionnelles du CRSH', NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (97, 5, 0, '1/Year', 'Prize', 0, 0, 0, 'Story Tellers', 'J''ai une histoire à raconter', NULL, 0, 0, 14);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (98, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'Bora Laskin National Fellowship (754)', 'Bourse canadienne Bora-Laskin', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (99, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'Jules and Gabrielle Léger (759)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (100, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'Queen''s Fellowship (220 or 321)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (101, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'Aileen D. Ross (230)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (102, 5, 0, '1/YR', 'Internships', 0, 0, 0, 'Mitacs Elevate', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (103, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Aid to Scholarly Journals (651)', 'Aide aux revues savantes', NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (104, 5, 0, '1/YR', 'Fellowships', 0, 0, 0, 'Centre for International Governance Innovation (CIGI)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (105, 5, 0, '1/YR', 'Fellowships', 0, 0, 0, 'CMHC Housing research Training Awards', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (106, 5, 0, '1+/YR', NULL, 0, 0, 0, 'Connection Grants (611)', 'Subventions Connections', NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (107, 5, 0, 'Open', NULL, 0, 0, 0, 'Department of National Defense Research Initiative (877)', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (108, 5, 0, '1/YR', 'Scholarship', 0, 0, 0, 'Doctoral Awards - CGS; Direct; National (752)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (109, 5, 0, '1+/Yr', 'Research Grants', 0, 0, 0, 'Insight Grants (435)', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (110, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Partnership Development Grants (890)', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (111, 5, 0, '1+/YR', 'Partnerships Programs', 0, 0, 0, 'Partnership Engage Grant', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (112, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Partnership Grants - Stage 1', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (113, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Partnership Grants - Stage 2', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (114, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'Postdoctoral Fellowships (756)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (115, 5, 0, 'Open', NULL, 0, 0, 0, 'Sports Participation Research Initative (862)', NULL, NULL, 0, 0, 10);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (116, 5, 0, 'Open', NULL, 0, 0, 0, 'Parental Leave - Scholarships & Fellowships (SSHRC) (769)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (117, 5, 0, 'Open', NULL, 0, 0, 0, 'Parental Leave - Scholarships and Fellowships through grants (SSHRC)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (118, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Parliamentary Internship Program (750)', 'Programme de stage parlementaire', NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (119, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Queen Elizabeth (774)', NULL, NULL, 0, 0, 13);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (120, 5, 0, '1/YR', NULL, 0, 0, 0, 'Special Initiatives Fund For Research Support And Collaboration', NULL, NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (121, 5, 0, '1/YR', NULL, 0, 0, 0, 'Research Support Fund (RSF)', NULL, NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (122, 5, 0, NULL, 'Partnerships Programs', 0, 0, 0, 'CECR Centres of Excellence for Commercialization and Research', ' Programme des centres d''excellence en commercialisation et en recherche', NULL, 0, 0, 7);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (123, 5, 0, '1+/YR', 'Scholarships', 0, 0, 0, 'Canada Graduate Scholarships Michael Smith Foreign Study Supplements (MSFSS)', 'Programme de bourses d''études supérieures du Canada - Suppléments pour études à l''étranger Michael-Smith', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (124, 5, 0, 'Open', 'Partnerships Programs', 0, 0, 0, 'Applied Research and Development Grants - Colleges (ARD)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (125, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'College - University Idea to Innovation Grants (CU-I2I)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (126, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Industrial Research Chairs for Colleges Grants (IRCC)', NULL, NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (127, 5, 0, '1/YR', 'Supplement', 0, 0, 0, 'Alice Wilson', 'Alice Wilson', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (128, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'Banting Postdoctoral Fellowships', 'Bourses postdoctorales Banting', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (129, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'Vanier', NULL, NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (130, 5, 0, '1/YR', 'Scholarships', 0, 0, 0, 'Canada Graduate Scholarship - Masters (CGSM)', 'Bourses d''études supérieures du Canada', NULL, 0, 0, 4);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (131, 5, 0, NULL, 'Partnerships Programs', 0, 0, 0, 'Business-Led Networks of Centres of Excellence program', 'Programme des réseaux de centres d''excellence dirigés par l''entreprise', NULL, 0, 0, 7);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (132, 5, 0, NULL, 'Partnerships Programs', 0, 0, 0, 'International Knowledge Translation Platforms initiative (IKTP)', 'Initiative de soutien international pour le transfert des connaissances (SITC)', NULL, 0, 0, 7);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (133, 5, 0, NULL, 'Partnerships Programs', 0, 0, 0, 'NCE Knowledge Mobilization (NCE-KM)', 'L''initiative de Mobilisation des connaissances (MC-RCE)', NULL, 0, 0, 7);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (134, 5, 0, NULL, 'Partnerships Programs', 0, 0, 0, 'Network for Centers of Excellence', 'Programme des réseaux de centres d''excellence (RCE)', NULL, 0, 0, 7);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (135, 5, 0, '1/YR', 'Partnerships Programs', 0, 0, 0, 'Technology Access Centre (TAC)', 'subventions d''établissement de centres d''accès à la technologie', NULL, 0, 0, 6);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (136, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Canadian Initiative on social Statistics', NULL, NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (137, 5, 0, '1/YR+', NULL, 0, 0, 0, 'Digging into Data', 'Au cœur des données numériques', NULL, 0, 0, 2);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (138, 5, 0, NULL, 'Partnerships Programs', 0, 0, 0, 'Research Partnerships Renewal Project (RPR)', NULL, NULL, 0, 0, 8);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (139, 5, 0, '1/YR for first year; unknown after that', 'Research Grant', 0, 0, 0, 'Frontiers in Research Fund - Stream 1', NULL, NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (140, 5, 0, '1/YR in second year; unknown after that', 'Research Grant', 0, 0, 0, 'Frontiers in Research Fund - Stream 2', NULL, NULL, 0, 0, 11);
INSERT INTO FUNDING_OPPORTUNITY_HISTORY VALUES (141, 5, 0, 'Unknown, but likely 1/YR in second year', 'Research Grant', 0, 0, 0, 'Frontiers in Research Fund - Special Calls', NULL, NULL, 0, 0, 11);

--POPULATES GRANTING_CAPABILITY TABLE
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 1, 2, 8);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 2, 2, 8);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 3, 2, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 4, 2, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 5, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 6, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 7, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 8, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 9, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 10, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 11, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 12, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 13, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 14, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 15, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 16, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 17, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 18, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 19, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 20, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 21, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 22, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 23, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 24, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 25, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 26, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 27, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 28, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 29, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 30, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 31, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 32, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 33, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 34, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 35, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 36, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 37, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 38, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 39, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 40, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 41, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 42, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 43, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 44, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 45, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 46, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 47, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 48, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 49, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 50, 2, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 51, 2, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 52, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 53, 2, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 54, 2, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 55, 2, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 56, 2, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 57, 2, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 58, 2, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 59, 2, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 60, 2, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 61, 2, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 62, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 63, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 64, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 65, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 66, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 67, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 68, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 69, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 70, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 71, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 72, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 73, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 74, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 75, 2, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 76, 2, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 77, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 78, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 81, 2, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 82, 2, 7);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 83, 2, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 84, 2, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 85, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 86, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 87, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 88, 2, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 89, 2, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 90, 2, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 91, 2, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 92, 2, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 93, 2, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 94, 2, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 95, 2, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 96, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 97, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 98, 2, 3);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 99, 2, 3);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 100, 2, 3);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 101, 2, 3);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 102, 2, 3);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 103, 2, 3);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 104, 2, 3);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 105, 2, 3);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 106, 2, 3);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 107, 2, 3);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 108, 2, 3);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 109, 2, 3);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 110, 2, 3);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 111, 2, 3);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 112, 2, 3);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 113, 2, 3);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 114, 2, 3);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 115, 2, 3);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 116, 2, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 118, 2, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 119, 2, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 120, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 121, 2, 7);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 122, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 123, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 124, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 125, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 126, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 127, 2, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 128, 2, 8);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 129, 2, 8);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 130, 2, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 131, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 132, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 133, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 134, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 135, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 136, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 137, 2, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 139, 2, 9);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 140, 2, 9);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 141, 2, 9);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 1, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 2, 4, 8);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 3, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 4, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 5, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 6, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 7, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 8, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 9, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 10, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 11, 4, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 12, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 13, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 14, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 15, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 16, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 17, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 18, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 19, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 20, 4, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 21, 4, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 22, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 23, 4, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 24, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 25, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 26, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 27, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 28, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 29, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 30, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 31, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 32, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 33, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 34, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 35, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 36, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 37, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 38, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 39, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 40, 4, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 41, 4, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 42, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 43, 4, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 44, 4, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 45, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 46, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 47, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 48, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 49, 4, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 50, 4, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 51, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 52, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 53, 4, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 54, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 55, 4, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 56, 4, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 57, 4, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 58, 4, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 59, 4, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 60, 4, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 61, 4, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 62, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 63, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 64, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 65, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 66, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 67, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 68, 4, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 69, 4, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 70, 4, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 71, 4, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 72, 4, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 73, 4, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 74, 4, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 75, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 76, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 77, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 78, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 81, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 82, 4, 7);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 83, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 84, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 85, 4, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 86, 4, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 87, 4, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 88, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 89, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 90, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 91, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 92, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 93, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 94, 4, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 95, 4, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 96, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 97, 4, 10);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 98, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 99, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 100, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 101, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 102, 4, 3);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 103, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 104, 4, 3);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 105, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 106, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 107, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 108, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 109, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 110, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 111, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 112, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 113, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 114, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 115, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 116, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 118, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 119, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 120, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 121, 4, 7);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 122, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 122, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 122, 4, 8);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 123, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 124, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 125, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 126, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 127, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 128, 4, 8);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 129, 4, 8);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 130, 4, 1);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 131, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 131, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 131, 4, 8);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 132, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 132, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 132, 4, 8);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 133, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 133, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 133, 4, 8);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 134, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 134, 4, 4);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 134, 4, 8);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 135, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 136, 4, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 137, 4, 6);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 139, 4, 9);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 140, 4, 9);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 141, 4, 9);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 79, 2, 12);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 79, 4, 12);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 80, 2, 12);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 80, 4, 12);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 117, 2, 12);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 117, 4, 12);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 138, 2, 5);
INSERT INTO GRANTING_CAPABILITY VALUES (NEXT VALUE FOR SEQ_GRANTING_CAPABILITY, NULL, NULL, 138, 4, 6);