--POPULATES ROLE TABLE
INSERT INTO ROLE VALUES(NEXT VALUE FOR SEQ_ROLE, 'Program Lead', 'Responsable du Programme');
INSERT INTO ROLE VALUES(NEXT VALUE FOR SEQ_ROLE, 'Program Officer', 'Agent de Programme');

--POPULATES ROLE AUDITING TABLE AND INSERTS THE CORRESPONDING METADATA INTO REVISION_INFO TABLE
INSERT INTO REVISION_INFO VALUES (NEXT VALUE FOR SEQ_REVISION_INFO, SYSDATETIME(), SYSTEM_USER);
INSERT INTO ROLE_HISTORY VALUES (1, 1, 0, 'Program Lead', 'Responsable du Programme');
INSERT INTO ROLE_HISTORY VALUES (2, 1, 0, 'Program Officer', 'Agent de Programme');

--POPULATES AGENCY TABLE
INSERT INTO AGENCY VALUES (NEXT VALUE FOR SEQ_AGENCY, 'SSHRC', 'CRSN', 'Social Sciences and Humanities Research Council', 'Conseil de Recherches en Sciences Humaines');
INSERT INTO AGENCY VALUES (NEXT VALUE FOR SEQ_AGENCY, 'NSERC', 'CRSNG', 'Natural Sciences and Engineering Research Council', STRINGDECODE('Conseil de Recherches en Sciences Naturelles et en G\u00e9nie'));
INSERT INTO AGENCY VALUES (NEXT VALUE FOR SEQ_AGENCY, 'CIHR', 'IRSC', 'Canadian Institutes of Health Research', STRINGDECODE('Instituts de Recherche en Sant\u00e9'));

--POPULATES AGENCY AUDITING TABLE AND INSERTS THE CORRESPONDING METADATA INTO REVISION_INFO TABLE
INSERT INTO REVISION_INFO VALUES (NEXT VALUE FOR SEQ_REVISION_INFO, SYSDATETIME(), SYSTEM_USER);
INSERT INTO AGENCY_HISTORY VALUES (1, 2, 0, 'SSHRC', 'CRSN', 'Social Sciences and Humanities Research Council', 'Conseil de Recherches en Sciences Humaines');
INSERT INTO AGENCY_HISTORY VALUES (2, 2, 0, 'NSERC', 'CRSNG', 'Natural Sciences and Engineering Research Council', STRINGDECODE('Conseil de Recherches en Sciences Naturelles et en G\u00e9nie'));
INSERT INTO AGENCY_HISTORY VALUES (3, 2, 0, 'CIHR', 'IRSC', 'Canadian Institutes of Health Research', STRINGDECODE('Instituts de Recherche en Sant\u00e9'));

-- POPULTATES GRANTING_SYSTEM TABLE
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'RP1', 'Research Portal', 'Portail de Recherche');
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'CRM', 'CRM', 'CRM');  
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'SSHRC Online', 'SSHRC Online', 'SSHRC Online');
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'AMIS', 'AMIS', 'AMIS');
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'NSERC Online', 'NSERC Online', 'NSERC Online');
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'NAMIS', 'NAMIS', 'NAMIS');
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'CIMS', 'Corporate Inventory Management System', 'Corporate Inventory Management System');
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'ResearchNet', 'ResearchNet', 'ResearchNet');
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'Convergence', 'Convergence', 'Convergence');
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'SP Secure Upload', 'SharePoint Secure Upload', STRINGDECODE('T\u00e9l\u00e9chargement S\u00e9curis\u00e9 SharePoint'));
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'SP Review', 'SharePoint Review', 'Examen de SharePoint');
INSERT INTO GRANTING_SYSTEM VALUES (NEXT VALUE FOR SEQ_GRANTING_SYSTEM, 'N/A', 'N/A', 'N/A');